// Marktorientiertes Management (MOM1IL) – Fragen im Klausurformat:
// Mehrfachauswahl, mindestens eine Antwort ist richtig, es können auch alle richtig sein.
//   quelle        – "Klausur …" (Frage aus einer alten Prüfung) oder "Skriptum" (aus den Folien erstellt)
//   antworten     – t: Text, r: true = richtig
//   musterantwort – Kernaussagen laut Skriptum (wird nach dem Antworten gezeigt)
//   seiten        – Foliennummern im Skriptum (WS 2026/27, Gaubinger)
// Die richtigen Antworten stammen aus dem Skriptum, nicht aus den Kreuzen in den Klausurfotos.
window.FAECHER = window.FAECHER || [];
{
const THEMEN = {
  grund: "Grundlagen & Säulen des Marketing",
  b2b: "Industriegüter / B2B",
  sit: "Situationsanalyse",
  mafo: "Marktforschung",
  strat: "Strategie",
  leist: "Leistungspolitik",
  preis: "Preismanagement",
  dist: "Distribution",
  komm: "Kommunikation",
};

const FRAGEN = [
  // ───────────── Fragen aus alten Klausuren ─────────────
  {
    thema: "strat", quelle: "Klausur 2024",
    frage: "Welche der folgenden Strategien zählt Porter zu den wesentlichen (generischen) Wettbewerbsstrategien?",
    antworten: [
      { t: "Skimmingstrategie" },
      { t: "Diversifikation" },
      { t: "Marktpenetration" },
      { t: "Differenzierung", r: true },
      { t: "Kostenführerschaft", r: true },
    ],
    musterantwort: "Porter unterscheidet Leistungsvorteil (Singularität) vs. Kostenvorteil und Gesamtmarkt vs. Teilmarkt → Differenzierung, Kostenführerschaft (und Fokus auf ein Segment). Größter Strategiefehler: „stuck in the middle“.",
    erklaerung: "Skimming und Penetration sind Preisstrategien (Preismanagement), keine generischen Wettbewerbsstrategien.",
    seiten: "Folie 145–147",
  },
  {
    thema: "grund", quelle: "Klausur 2024",
    frage: "Aus welchen Komponenten setzt sich der Wertgewinn zusammen?",
    antworten: [
      { t: "Kundensumme" },
      { t: "Wertsumme", r: true },
      { t: "Erlössumme" },
      { t: "Kostensumme", r: true },
    ],
    musterantwort: "Wertgewinn (Nettonutzenvorteil) = Wertsumme (Produktnutzen i.e.S., Service, Image, Ästhetik, Mitarbeiter …) − Kostensumme (Kaufpreis, Schulung, Energie, Entsorgung …).",
    erklaerung: "Der Kunde wählt das Angebot, das ihm subjektiv den größten Wertgewinn bringt.",
    seiten: "Folie 17, 34",
  },
  {
    thema: "grund", quelle: "Klausur 2024",
    frage: "Was steht im Zentrum des Marketingansatzes / -verständnisses?",
    antworten: [
      { t: "Bedürfnisse der Mitarbeiter" },
      { t: "Bedürfnisse der Mitbewerber" },
      { t: "Bedürfnisse der Lieferanten" },
      { t: "Bedürfnisse der Kunden", r: true },
      { t: "Bedürfnisse der Substitutionsanbieter" },
      { t: "Bedürfnisse der Kooperationspartner" },
    ],
    musterantwort: "Marketingkonzept: Bedürfnisse der Zielmärkte ermitteln und wirkungsvoller und wirtschaftlicher befriedigen als die Wettbewerber – so, dass die Lebensqualität der Gesellschaft bewahrt oder verbessert wird (Kotler).",
    erklaerung: "Erste Säule des Marketing: Orientierung an Kundenbedürfnissen.",
    seiten: "Folie 12, 14",
  },
  {
    thema: "sit", quelle: "Klausur 2024",
    frage: "Wie berechnet man den eigenen relativen Marktanteil?",
    antworten: [
      { t: "Absatzvolumen des eigenen Unternehmens / Marktvolumen" },
      { t: "Absatzvolumen / Absatzpotenzial" },
      { t: "Absatzpotenzial · Marktvolumen" },
      { t: "Absatzvolumen des Konkurrenten / Marktvolumen" },
      { t: "Absatzvolumen des Mitbewerbs / Absatzvolumen des eigenen Unternehmens" },
      { t: "Absatzvolumen des eigenen Unternehmens / Absatzvolumen des stärksten Konkurrenten", r: true },
    ],
    musterantwort: "Relativer Marktanteil = Marktanteil des eigenen Unternehmens / Marktanteil des stärksten Konkurrenten (gleichbedeutend: eigenes Absatzvolumen / Absatzvolumen des stärksten Konkurrenten).",
    erklaerung: "Absatzvolumen / Marktvolumen · 100 ist der (absolute) Marktanteil in %.",
    seiten: "Folie 75",
  },
  {
    thema: "leist", quelle: "Klausur 2024",
    frage: "Welche Hauptdimensionen charakterisieren die Portfoliomatrix der Boston Consulting Group (BCG-Matrix)?",
    antworten: [
      { t: "Marktattraktivität" },
      { t: "Marktgröße" },
      { t: "relative Wettbewerbsstärke" },
      { t: "relativer Marktanteil", r: true },
      { t: "relative Marktgröße" },
      { t: "Marktwachstum", r: true },
    ],
    musterantwort: "BCG-Matrix: x-Achse relativer Marktanteil (0,1 – 1 – 10), y-Achse Marktwachstum pro Jahr. Felder: Question Mark, Star, Cash Cow, Poor Dog.",
    erklaerung: "Marktattraktivität und relative Wettbewerbsstärke sind die Achsen eines anderen Portfolios (McKinsey), nicht der BCG-Matrix.",
    seiten: "Folie 162–163",
  },
  {
    thema: "grund", quelle: "Klausur WS23 / Moodle",
    frage: "Welche der folgenden Aussagen zum Begriff „Kundennutzen“ sind richtig?",
    antworten: [
      { t: "Unter Kundennutzen versteht man die Fähigkeit eines Angebots, ein Kundenbedürfnis zu befriedigen", r: true },
      { t: "Kundennutzen umfasst eine Vielzahl an Aspekten wie Produktnutzen, Servicenutzen oder Beziehungsnutzen", r: true },
      { t: "Kundennutzen spielt auf Industriegütermärkten keine Rolle, hier wird nur auf Basis des Preises entschieden" },
      { t: "Kundennutzen und Wert sind im Grunde genommen dasselbe" },
      { t: "Kundennutzen hängt einzig und allein von einer überragenden Produktqualität ab" },
    ],
    musterantwort: "Nutzen entsteht aus vielen Aspekten (Produktnutzen i.e.S., Service, Image, Ästhetik, Mitarbeiter). Viele Bereiche des Unternehmens (Wertkette) tragen dazu bei. Wert(gewinn) = Nutzen (Wertsumme) − Kosten (Kostensumme) – also nicht dasselbe wie Nutzen.",
    erklaerung: "Auch im B2B zählt der Nettonutzen, nicht nur der Preis (z. B. nutzenbasierte Preisbildung im Chemieunternehmen).",
    seiten: "Folie 17–20, 36, 180",
  },
  {
    thema: "grund", quelle: "Klausur WS23 / Moodle",
    frage: "Welche der folgenden Aussagen zum Thema Kundenzufriedenheit treffen zu?",
    antworten: [
      { t: "Kundenzufriedenheit entsteht durch einen Vergleich der erwarteten mit der tatsächlich wahrgenommenen Leistung", r: true },
      { t: "Liegt die wahrgenommene Leistung über der erwarteten, spricht man von positiver Diskonfirmation", r: true },
      { t: "Die größte Gefahr geht bei unzufriedenen Kunden davon aus, dass sie (still) zur Konkurrenz abwandern und ihre Unzufriedenheit anderen mitteilen", r: true },
      { t: "Liegt die wahrgenommene Leistung über der erwarteten, spricht man von negativer Diskonfirmation" },
      { t: "Kundenzufriedenheit kann bereits vor dem Kauf entstehen, wenn ein Anbieter besonders positive Werbung über sein Produkt macht" },
    ],
    musterantwort: "Kundenzufriedenheit ist ein Nachkaufphänomen: Der Kunde beurteilt Produkte/Dienstleistungen anhand seiner Nutzungserfahrungen – Übereinstimmung zwischen subjektiven Erwartungen und tatsächlich erlebter Motivbefriedigung. Unzufriedene Kunden wandern (still) ab (Unvoiced Complainers), beschweren sich oder betreiben negative Mund-zu-Mund-Propaganda.",
    erklaerung: "Weil sie erst nach dem Kauf entsteht, kann Werbung allein keine Zufriedenheit erzeugen.",
    seiten: "Folie 23",
  },
  {
    thema: "b2b", quelle: "Klausur WS23 / Moodle",
    frage: "Welche der folgenden Aussagen zum Begriff „Industriegütermarketing“ sind zutreffend?",
    antworten: [
      { t: "Industriegütermarketing richtet sich auf Organisationen als Abnehmer aus, die selber wieder Leistungen erstellen", r: true },
      { t: "In Industriegütermärkten entscheiden typischerweise mehrere Personen in einem Kaufprozess", r: true },
      { t: "Industriegüter weisen typischerweise eine sehr niedrige Individualisierung auf" },
      { t: "Im Industriegütermarketing werden ausschließlich physische Produkte vermarktet" },
      { t: "Industriegütermarketing umfasst auch die Vermarktung an private Endabnehmer" },
    ],
    musterantwort: "Industriegüter definieren sich über den Abnehmer (Organisationen) und können auch Dienstleistungen sein. Industriegütermarketing wendet sich nicht an private Endabnehmer und schließt reine Distributoren (Handel) aus – B2B-Marketing umfasst auch den Handel. B2B: mehrere Entscheider, hohe Individualisierung, formalisierter Bedarf, hohe Interaktion.",
    erklaerung: "B2C: geringe Individualisierung – B2B: hohe Individualisierung (→ Co-Development).",
    seiten: "Folie 45, 48",
  },
  {
    thema: "sit", quelle: "Klausur WS23 / Moodle",
    frage: "Welche der folgenden Aussagen zum „Buying Center“ treffen zu?",
    antworten: [
      { t: "Ein Buying Center kann sowohl formell als auch informell gebildet werden", r: true },
      { t: "Das Buying Center muss vom anbietenden Unternehmen umfassend analysiert werden, unter anderem sind dabei folgende Bereiche relevant: Umfang und Struktur, Rollen der beteiligten Personen, Informations- und Entscheidungsverhalten", r: true },
      { t: "Unter der Rolle „User“ versteht man den tatsächlichen Verwender des zu beschaffenden Produkts", r: true },
      { t: "Man versteht darunter die gedankliche Zusammenfassung aller am Kaufprozess beteiligten Personen", r: true },
      { t: "Unter der Rolle „Gatekeeper“ versteht man den sogenannten „Informationsselektierer“, der verschiedenste Informationen aufbereitet und im Buying Center verteilt", r: true },
    ],
    musterantwort: "Buying Center = gedankliche Zusammenfassung aller am Kaufprozess beteiligten Personen (Decision-Making-Unit), informell oder institutionell verankert. Rollen: User, Influencer, Buyer, Decider, Gatekeeper. Zu analysieren: Umfang & Struktur, Rollen, Bedürfnisse/Zufriedenheit, Informations- und Entscheidungsverhalten.",
    erklaerung: "Hier sind alle Antworten richtig – das kommt im Klausurformat vor („es können auch alle Antworten richtig sein“).",
    seiten: "Folie 71–73",
  },
  {
    thema: "sit", quelle: "Klausur WS23 / Moodle",
    frage: "Welche der folgenden Tools eignen sich zur alleinigen Analyse der eigenen Stärken und Schwächen im Rahmen der Unternehmensanalyse?",
    antworten: [
      { t: "VRIO-Methode", r: true },
      { t: "Wertkettenanalyse", r: true },
      { t: "PESTEL-Analyse" },
      { t: "Personas" },
      { t: "SWOT-Analyse" },
    ],
    musterantwort: "Die Wertkette ist Ausgangspunkt zur Analyse von Fähigkeiten und Kernkompetenzen. PESTEL analysiert das Makroumfeld, Personas beschreiben Kunden. Die SWOT-Analyse verbindet Stärken/Schwächen mit Chancen/Risiken – sie ist also keine alleinige Analyse der eigenen Stärken und Schwächen.",
    erklaerung: "VRIO wurde in der korrigierten Klausur WS23 als richtig gewertet, kommt im aktuellen Skriptum aber nicht vor.",
    seiten: "Folie 83, 88, 92",
  },
  {
    thema: "mafo", quelle: "Klausur WS23",
    frage: "Welche der folgenden Aussagen zur Marktforschung bzw. Informationsversorgung treffen zu?",
    antworten: [
      { t: "Die Informationsversorgung spielt in allen Schritten über den gesamten Marketing-Management-Prozess eine wichtige Rolle", r: true },
      { t: "Im Marketing gibt es eine sehr enge Verbindung zwischen Informationsbedarf und Entscheidungsfindung", r: true },
      { t: "Marktforschung ist eigentlich nur während der Situationsanalyse von Bedeutung und spielt im operativen Marketing nur eine geringe Rolle" },
      { t: "In der Marktforschung geht es darum, so viele Daten wie nur möglich zu sammeln, ungeachtet ihrer Qualität oder Herkunft" },
    ],
    musterantwort: "Im Marketing-Management-Prozess begleitet die Informationsversorgung alle Phasen. Marketingforschung liefert Daten und Befunde, die für Marketingentscheidungen benötigt werden – Datenerhebung allein reicht nicht, entscheidend ist die Transformation in entscheidungsunterstützende Insights.",
    erklaerung: "Sekundärdaten müssen auf Relevanz, Vollständigkeit, Aktualität, Vergleichbarkeit und Genauigkeit geprüft werden.",
    seiten: "Folie 41, 102–103, 111",
  },
  {
    thema: "mafo", quelle: "Klausur WS23 / Moodle",
    frage: "Welche der folgenden Aussagen zur Sekundärforschung sind zutreffend?",
    antworten: [
      { t: "Ein Vorteil der Sekundärforschung liegt darin, dass die durchzuführende Primärforschung unter Umständen nicht mehr so aufwändig gestaltet werden muss", r: true },
      { t: "Sekundärforschung bedeutet die Auswertung von bereits vorhandenen Daten, die ursprünglich für andere Zwecke erhoben wurden", r: true },
      { t: "Ein Nachteil der Sekundärforschung liegt in den hohen Kosten" },
      { t: "Sekundärdaten von wissenschaftlichen Institutionen kann eigentlich ohne weitere Prüfung immer vertraut werden" },
      { t: "Daten aus internationaler Sekundärforschung kann man ohne Weiteres auch auf das eigene Marktforschungsproblem anwenden" },
    ],
    musterantwort: "Sekundärforschung = Auswertung vorhandener Daten, die für andere Zwecke erhoben wurden; sollte immer am Beginn stehen. Vorteile: Präzisierung der Forschungsziele, evtl. Entfall/Reduktion der Primärforschung, Kosten- und Zeitvorteile. Nachteile: beschränkte Relevanz, Vollständigkeit, Aktualität, Vergleichbarkeit (v. a. international), Genauigkeit.",
    erklaerung: "Kosten sind ein Vorteil, kein Nachteil. Die Genauigkeit ist oft schwer zu beurteilen, weil Infos zur Methodik fehlen – daher immer prüfen.",
    seiten: "Folie 107, 111–113",
  },
  {
    thema: "strat", quelle: "Klausur WS23",
    frage: "Welche der folgenden Aussagen zu den Wettbewerbsstrategien eines Unternehmens treffen zu?",
    antworten: [
      { t: "Unter Differenzierung versteht man ein einzigartiges Leistungsangebot, welches sich z. B. durch höhere Qualität, Image, Service oder Innovation vom Mitbewerb abhebt", r: true },
      { t: "Eine große Gefahr für Unternehmen ist eine unklare strategische Ausrichtung („stuck in the middle“)", r: true },
      { t: "Unter Kostenführerschaft versteht man das Anbieten möglichst billiger Preise für die Kunden unabhängig von der eigenen Kostenstruktur" },
      { t: "Wenn ein Unternehmen eine Differenzierungsstrategie verfolgt, dann spielt das Management der eigenen Kosten überhaupt keine Rolle" },
    ],
    musterantwort: "Differenzierung: Einzigartigkeit (außer Preis), höherer preispolitischer Spielraum (Qualität, Image, Service, Innovation, Schnelligkeit). Kostenführerschaft: breites Sortiment zu niedrigen Preisen, hohe Marktanteile, Erfahrungskurveneffekte, effiziente Produktion notwendig. Größter Fehler: „stuck in the middle“.",
    erklaerung: "Auch der Differenzierer hat Kosten – sein Zusatzgewinn entsteht nur, wenn der Mehrpreis die Zusatzkosten übersteigt.",
    seiten: "Folie 145–147",
  },
  {
    thema: "leist", quelle: "Klausur WS23 / Moodle",
    frage: "Welche der folgenden Aussagen zur Leistungspolitik eines Unternehmens treffen zu?",
    antworten: [
      { t: "Oberstes Ziel bei der Gestaltung eines Produktprogramms ist ein ausgewogenes Portfolio in Hinblick auf Wachstum und Liquidität", r: true },
      { t: "Produkte sollten in erster Linie auf Basis ihres Umsatzes beurteilt werden" },
      { t: "Unter Produktvariation versteht man ein zeitlich paralleles Angebot mehrerer Produktvarianten, um unterschiedliche Zielgruppen zu adressieren" },
      { t: "Unter Produktdifferenzierung versteht man die Einführung eines Neuprodukts, welches das Vorgängerprodukt ablöst" },
    ],
    musterantwort: "Produktinnovation = Entwicklung von Neuprodukten; Produktvariation = Veränderung bereits eingeführter Produkte; Produktdifferenzierung = zeitlich paralleles Angebot mehrerer Varianten; Produktelimination = Produkte werden vom Markt genommen. Portfolioanalysen zielen auf Ausgewogenheit hinsichtlich Wachstum und Liquidität; Entscheidungen brauchen mehr als kurzfristige Umsatzbetrachtung.",
    erklaerung: "Achtung Verwechslungsgefahr: Das „zeitlich parallele Angebot mehrerer Varianten“ ist Differenzierung, nicht Variation.",
    seiten: "Folie 153, 162, 167",
  },
  {
    thema: "dist", quelle: "Klausur WS23",
    frage: "Welche der folgenden Aussagen zum Distributionsmanagement eines Unternehmens treffen zu?",
    antworten: [
      { t: "Unter Direktvertrieb versteht man die Distribution von Unternehmensleistungen ohne Absatzmittler", r: true },
      { t: "Unter indirektem Vertrieb versteht man die Distribution von Leistungen über Absatzmittler wie Groß- und Einzelhandel oder Vertriebspartner", r: true },
      { t: "Vertriebsorgane können beispielsweise durch Verkaufsunterlagen (Argumentationsleitfäden, Prospekte, Präsentationen), Experten oder Schulungen unterstützt werden", r: true },
      { t: "Entscheidungen im Distributionsmanagement haben nur einen geringen Einfluss auf die Wettbewerbsfähigkeit eines Unternehmens und haben typischerweise nur kurzfristigen Charakter" },
    ],
    musterantwort: "Zentrale Aufgabe: den geschaffenen Wert den Kunden (physisch) zugänglich machen. Entscheidungsfelder: Gestaltung des Distributionssystems (akquisitorisch: Absatzkanalstruktur; logistisch), Steuerung und Unterstützung der Vertriebsorgane, ergebnisbezogenes Controlling. Direktvertrieb: unternehmensinterne Organe; indirekt: rechtlich/wirtschaftlich selbständige externe Organe.",
    erklaerung: "Unterstützung der Vertriebsorgane: Verkaufsunterlagen, Expert*innen-Unterstützung, Schulungen.",
    seiten: "Folie 185–186, 190",
  },
  {
    thema: "dist", quelle: "Moodle-Test",
    frage: "Welche Aussagen zum Distributionsmanagement eines Unternehmens treffen zu?",
    antworten: [
      { t: "Unter indirektem Vertrieb versteht man die Distribution von Leistungen über Absatzmittler wie Groß- und Einzelhandel oder Vertriebspartner", r: true },
      { t: "Unter exklusiver Distribution versteht man die Beschränkung auf sehr ausgewählte Absatzmittler", r: true },
      { t: "Unter intensiver Distribution versteht man die Beschränkung auf sehr ausgewählte Absatzmittler" },
      { t: "Unter Direktvertrieb versteht man die Distribution von Unternehmensleistungen ohne Absatzmittler", r: true },
      { t: "Unternehmen sollten grundsätzlich immer so viele Distributionskanäle wie nur möglich abdecken" },
    ],
    musterantwort: "Die Breite eines Vertriebskanals ist die Anzahl der auf einer Vertriebsstufe eingesetzten Vertriebspartner: exklusiv = sehr wenige, ausgewählte Absatzmittler; intensiv = möglichst viele. Die Zahl der Kanäle ist eine bewusste Gestaltungsentscheidung, nicht „so viele wie möglich“.",
    erklaerung: "Die Begriffe „exklusiv/intensiv“ stehen nicht wörtlich im aktuellen Skriptum – sie beschreiben die Breite des Vertriebskanals (Folie 187).",
    seiten: "Folie 186–187",
  },
  {
    thema: "mafo", quelle: "Moodle-Test",
    frage: "Welche der folgenden Aussagen treffen auf die verschiedenen Formen der Befragung zu?",
    antworten: [
      { t: "Die persönliche Befragung ist zwar kosten- und zeitaufwändig, dafür lassen sich aber auch längere Fragebögen mit speziellem Inhalt abfragen", r: true },
      { t: "Ein Vorteil der telefonischen Befragung ist die Tatsache, dass man auch sehr lange Interviews führen kann" },
      { t: "Bei Online-Befragungen kann man in der Regel von einer sehr hohen Rücklaufquote ausgehen" },
      { t: "Schriftliche Befragungen kommen heute noch genau so häufig zum Einsatz wie vor etwa 10 Jahren" },
      { t: "Der Einfluss eines Interviewers ist vor allem bei der schriftlichen Befragung besonders hoch" },
    ],
    musterantwort: "Persönlich: Kosten und Zeitaufwand hoch, Rücklauf hoch, Interviewereinfluss hoch, komplexe Inhalte sehr gut, möglicher Umfang hoch. Telefonisch: Umfang mittel. Online: Kosten sehr niedrig, Rücklauf mittel, kein Interviewereinfluss, Reichweite sehr hoch. Schriftlich: Rücklauf niedrig, kein Interviewereinfluss. Faustregel: Je komplexer das Thema, desto eher persönliche/moderierte Formate.",
    erklaerung: "Bei schriftlicher und Online-Befragung gibt es keinen Interviewer – also auch keinen Interviewereinfluss.",
    seiten: "Folie 120–121",
  },
  {
    thema: "mafo", quelle: "Moodle-Test",
    frage: "Welche der folgenden Aussagen zum Begriff „Stichprobe“ treffen zu?",
    antworten: [
      { t: "Eine Stichprobe kann entweder auf dem Zufalls- oder dem Quotenprinzip beruhen", r: true },
      { t: "Eine Stichprobe ist dann repräsentativ, wenn diese ein verkleinertes, aber sonst wirklichkeitsgetreues Abbild der Grundgesamtheit darstellt", r: true },
      { t: "Eine Stichprobe stellt einen Teil der Grundgesamtheit von relevanten Untersuchungsobjekten dar", r: true },
      { t: "Beim sog. Quotenverfahren kann man immer davon ausgehen, dass der Quotenplan auch zuverlässig von den Interviewern eingehalten wird" },
      { t: "Da die Bestimmung einer Grundgesamtheit sehr kompliziert ist, empfiehlt sich eigentlich immer eine sog. Vollerhebung" },
    ],
    musterantwort: "Stichprobe = Teil einer Grundgesamtheit relevanter Untersuchungsobjekte; aus der Teilerhebung soll möglichst exakt auf die Grundgesamtheit geschlossen werden. Repräsentativ = verkleinertes, aber wirklichkeitsgetreues Abbild. Auswahl: Zufallsverfahren (einfach, geschichtet, Klumpen) oder Quotenverfahren; Sonderform Snowball Sampling.",
    erklaerung: "Die dritte Aussage ist wörtlich die Definition aus dem Skriptum (Folie 129).",
    seiten: "Folie 129–135",
  },
  {
    thema: "strat", quelle: "Moodle-Test (offene Frage)",
    frage: "Beschreiben Sie, was man grundsätzlich unter dem Begriff „Differenzierung“ versteht und welche Möglichkeiten bzw. Ansatzpunkte ein Unternehmen hat, um sich zu differenzieren. – Welche Aussagen treffen zu?",
    antworten: [
      { t: "Differenzierung bedeutet, ein einzigartiges Leistungsangebot zu schaffen, das sich – außer über den Preis – vom Mitbewerb abhebt", r: true },
      { t: "Ansatzpunkte sind z. B. Qualität, Image, Service, Innovation oder Schnelligkeit", r: true },
      { t: "Eine erfolgreiche Differenzierung verschafft einen höheren preispolitischen Spielraum", r: true },
      { t: "Differenzierung bedeutet vor allem, dauerhaft niedrigere Preise als die Mitbewerber anzubieten" },
      { t: "Differenzierung ist nur für Konsumgüter möglich, nicht für Industriegüter" },
    ],
    musterantwort: "Differenzierung (Porter): Einzigartigkeit außer Preis, höherer preispolitischer Spielraum; Möglichkeiten: Qualität, Image, Service, Innovation, Schnelligkeit … Wird sie mit Kostenführerschaft vermischt, droht „stuck in the middle“.",
    erklaerung: "Nicht verwechseln mit Produktdifferenzierung (Leistungspolitik) = zeitlich paralleles Angebot mehrerer Produktvarianten.",
    seiten: "Folie 145–146, 153",
  },
  {
    thema: "sit", quelle: "Klausur WS23 / Moodle (offene Frage)",
    frage: "Sie sind Marketing Manager bei einem Stahlhersteller und sollen die Makroumwelt analysieren. Nennen und beschreiben Sie das geeignete Tool und wenden Sie es exemplarisch an. – Welche Aussagen treffen zu?",
    antworten: [
      { t: "Das geeignete Tool ist die PESTEL-Analyse: Political, Economical, Social, Technological, Ecological, Legal", r: true },
      { t: "Zentrale Fragestellung ist: „Welche Themen in diesem Analysebereich beeinflussen meine Branche?“", r: true },
      { t: "Beispiel: EU-Klimaziele und CO₂-Vorgaben betreffen den politischen bzw. rechtlichen Bereich, „grüner Stahl“ und Recycling den ökologischen", r: true },
      { t: "Das geeignete Tool für die Makroumwelt ist Porters Five Forces Modell" },
      { t: "Die Makroanalyse untersucht vor allem die eigenen Stärken und Schwächen des Stahlherstellers" },
    ],
    musterantwort: "PESTEL: Politisch (Wirtschafts-/Konjunkturpolitik, Subventionen, Förderungen), Ökonomisch (Wirtschaftsdaten, Kapitalmarkt, Branchenstruktur, Arbeitskräftepotenzial), Soziokulturell (Bevölkerungsentwicklung, Wertewandel, Megatrends), Technologisch (neue Materialien, Technologie-/Produktlebenszyklen), Ökologisch (natürliche Ressourcen, Recyclingpotenzial), Rechtlich (Gesetze, Rechtsprechung, Patente, Umwelt). Datenquellen je Bereich angeben.",
    erklaerung: "Five Forces gehört zur Mikro-Umfeldanalyse (Branche/Wettbewerb); Stärken/Schwächen zur Unternehmensanalyse.",
    seiten: "Folie 57–65, 68",
  },
  {
    thema: "strat", quelle: "Moodle-Test (offene Frage)",
    frage: "Beschreiben Sie kurz, wie die strategische Grundausrichtung eines Unternehmens mit der operativen Umsetzung bzw. der Planung des Marketing-Programms zusammenhängt. – Welche Aussagen treffen zu?",
    antworten: [
      { t: "Strategie heißt, die richtigen Dinge zu tun (WAS); operativ heißt, die Dinge richtig zu tun (WIE)", r: true },
      { t: "Die strategische Planung gibt den Rahmen für die operative Umsetzung (Marketinginstrumente / Marketing-Mix) vor", r: true },
      { t: "Inkonsistenzen zwischen Strategie und Marketing-Mix führen zu innerbetrieblichen Ineffizienzen und Dissonanzen beim Kunden", r: true },
      { t: "Produkt-, Preis-, Distributions- und Kommunikationspolitik werden unabhängig von der Strategie geplant" },
      { t: "Die Strategie legt fest, WIE etwas umgesetzt wird; die operative Ebene legt fest, WAS erreicht werden soll" },
    ],
    musterantwort: "Strategische Planung (Vision, Ziele, Unternehmens- und Bereichsstrategien) gibt den Rahmen vor; Produkt-, Kommunikations-, Distributions- und Preispolitik müssen sich daran orientieren. Inkonsistenzen → Ineffizienzen und Dissonanzen beim Kunden.",
    erklaerung: "Merksatz: Strategie = die richtigen Dinge tun (WAS), operativ = die Dinge richtig tun (WIE).",
    seiten: "Folie 143, 148",
  },
  {
    thema: "grund", quelle: "Klausur 2024 (offene Frage)",
    frage: "Wie kann Kundenzufriedenheit definiert werden und warum ist die Kundenzufriedenheit eine wesentliche Zielgröße im Marketing? – Welche Aussagen treffen zu?",
    antworten: [
      { t: "Kundenzufriedenheit ist ein Nachkaufphänomen, bei dem der Kunde Produkte oder Dienstleistungen anhand seiner Nutzungserfahrungen beurteilt", r: true },
      { t: "Sie drückt die Übereinstimmung zwischen subjektiven Erwartungen und tatsächlich erlebter Motivbefriedigung aus", r: true },
      { t: "Unzufriedene Kunden wandern oft still ab (Unvoiced Complainers), beschweren sich oder verbreiten negative Mund-zu-Mund-Propaganda", r: true },
      { t: "Zufriedene Kunden zu binden ist eine eigene Kundenstrategie – Kundenzufriedenheit ist Basis für den Erfolg, aber nicht alles", r: true },
      { t: "Kundenzufriedenheit ist nur dann relevant, wenn ein Unternehmen der Preisführer ist" },
    ],
    musterantwort: "Definition wie im Skriptum (Nachkaufphänomen, Erwartung vs. erlebte Motivbefriedigung). Zielgröße, weil „Zielerreichung durch zufriedene Kunden“ eine Säule des Marketing ist: Bindung bestehender Kunden (defensive Kundenstrategie) statt nur Neukundengewinnung; Unzufriedenheit führt zu Abwanderung und negativer Mundpropaganda.",
    erklaerung: "In der Klausur-Antwort genannte Vorteile zufriedener Kunden (Wiederkauf, Preisspielraum, Cross-Selling, Empfehlungen) passen dazu.",
    seiten: "Folie 14, 21–24",
  },
  {
    thema: "sit", quelle: "Klausur 2024 (offene Frage)",
    frage: "Sie leiten das strategische & operative Marketing eines Photovoltaik-Unternehmens und sollen eine umfassende Situationsanalyse durchführen. Welche Methoden und Aktivitäten gehören in die einzelnen Prozessphasen? – Welche Aussagen treffen zu?",
    antworten: [
      { t: "Makroumfeld: PESTEL-Analyse (z. B. Förderungen, Energiepolitik, neue Zelltechnologien)", r: true },
      { t: "Mikroumfeld: Markt (Marktpotenzial/-volumen, Marktanteil), Kunden (z. B. Buying Center) und Wettbewerb (z. B. Five Forces, Konkurrenzanalyse)", r: true },
      { t: "Unternehmensanalyse: erfolgskritische Faktoren in Checkliste bewerten und als Stärken-Schwächen-Profil im Vergleich zum Mitbewerb darstellen", r: true },
      { t: "SWOT: Stärken/Schwächen den Chancen/Risiken gegenüberstellen (TOWS-Matrix) und daraus strategische Handlungsoptionen ableiten", r: true },
      { t: "Chancen und Risiken ergeben sich aus der Unternehmensanalyse, Stärken und Schwächen aus der Umfeldanalyse" },
      { t: "Die Situationsanalyse beginnt mit der Festlegung des Marketing-Mix" },
    ],
    musterantwort: "Umfeldanalyse (Makro: PESTEL; Mikro: Markt, Kunden, Wettbewerb) → Chancen/Risiken (bewertet nach Erfolgs-/Gefährdungspotenzial und Eintrittswahrscheinlichkeit). Unternehmensanalyse → Stärken/Schwächen-Profil. SWOT/TOWS-Matrix → Handlungsoptionen (S-O, W-O, S-T, W-T).",
    erklaerung: "Umfeld → Chancen/Risiken, Unternehmen → Stärken/Schwächen. Der Marketing-Mix kommt erst nach Situationsanalyse und Strategie.",
    seiten: "Folie 53–57, 85–86, 88–95",
  },
  {
    thema: "grund", quelle: "Klausur 2024 (offene Frage)",
    frage: "Erläutern Sie stichwortartig und unter Zuhilfenahme einer Grafik das KANO-Modell. – Welche Aussagen treffen zu?",
    antworten: [
      { t: "Basisfaktoren werden als selbstverständlich vorausgesetzt; Nichterfüllung führt zu massiver Unzufriedenheit, Übererfüllung wird kaum honoriert (Auto: Rostschutz)", r: true },
      { t: "Leistungsfaktoren werden ausdrücklich verlangt; die Zufriedenheit steigt etwa proportional mit dem Erfüllungsgrad (Auto: Verbrauch)", r: true },
      { t: "Begeisterungsfaktoren sind unerwartet; fehlen sie, entsteht keine Unzufriedenheit, sind sie da, steigt die Zufriedenheit stark (Auto: Sonderausstattung)", r: true },
      { t: "Mit der Zeit werden Begeisterungsfaktoren zu Leistungs- bzw. Basisfaktoren", r: true },
      { t: "Basisfaktoren steigern bei Übererfüllung die Zufriedenheit überproportional" },
      { t: "Begeisterungsfaktoren werden vom Kunden ausdrücklich verlangt und sind ihm bewusst" },
    ],
    musterantwort: "Grafik: x-Achse Erfüllungsgrad, y-Achse Kundenzufriedenheit; Leistungsfaktoren als Gerade, Basisfaktoren als Kurve unten (nähert sich der Null), Begeisterungsfaktoren als Kurve oben (steigt exponentiell), Pfeil „Zeit“. Ziele: Einfluss der Anforderungen auf die Zufriedenheit abschätzen, maßgeschneiderte Leistungspakete, Prioritäten für die Produktentwicklung.",
    erklaerung: "Vorgehen der Kano-Methode: Anforderungen identifizieren (Vorstudie) → je Anforderung funktionale und dysfunktionale Frage → standardisierte Interviews → Auswertungstabelle.",
    seiten: "Folie 25–31",
  },
  {
    thema: "sit", quelle: "Klausur 2024 (offene Frage)",
    frage: "Stellen Sie den relativen Marktanteil dem absoluten Marktanteil bezüglich Ermittlung und Aussagekraft gegenüber. – Welche Aussagen treffen zu?",
    antworten: [
      { t: "Absoluter Marktanteil = Absatzvolumen / Marktvolumen · 100 (in %)", r: true },
      { t: "Relativer Marktanteil = Marktanteil des eigenen Unternehmens / Marktanteil des stärksten Konkurrenten", r: true },
      { t: "Der relative Marktanteil zeigt die Position im Vergleich zum stärksten Wettbewerber – ein Wert über 1 bedeutet Marktführerschaft", r: true },
      { t: "Absoluter Marktanteil = Absatzvolumen / Absatzpotenzial · 100" },
      { t: "Der relative Marktanteil ist immer ein Prozentwert zwischen 0 und 100" },
    ],
    musterantwort: "Der absolute Marktanteil sagt, welchen Anteil des Marktes ich habe – allein aber wenig über meine Wettbewerbsposition (5 % können Marktführerschaft oder Bedeutungslosigkeit sein, je nach Marktstruktur). Der relative Marktanteil setzt ihn ins Verhältnis zum stärksten Konkurrenten; er ist eine Achse der BCG-Matrix (0,1 – 1 – 10).",
    erklaerung: "Absatzvolumen / Absatzpotenzial ist die Ausschöpfung des eigenen Potenzials, kein Marktanteil.",
    seiten: "Folie 74–75, 163",
  },
  {
    thema: "sit", quelle: "Klausur 2024 (offene Frage)",
    frage: "Wer gilt als Wettbewerber und sollte somit bei der Konkurrenzanalyse berücksichtigt werden? – Welche Aussagen treffen zu?",
    antworten: [
      { t: "Die aktuellen Mitbewerber in der Branche", r: true },
      { t: "Abnehmer, die das Potenzial zur Rückwärtsintegration aufweisen", r: true },
      { t: "Lieferanten, die das Potenzial zur Vorwärtsintegration aufweisen", r: true },
      { t: "Hersteller von Substitutionsprodukten", r: true },
      { t: "Potenzielle neue Mitbewerber aus anderen Branchen", r: true },
      { t: "Ausschließlich Unternehmen, die ein identisches Produkt anbieten" },
    ],
    musterantwort: "Porters Five Forces zeigt, wen man aufnehmen soll: aktuelle Mitbewerber sowie alle potenziellen – Abnehmer mit Rückwärtsintegrationspotenzial, Lieferanten mit Vorwärtsintegrationspotenzial, Substitutionsanbieter, neue Mitbewerber aus anderen Branchen.",
    erklaerung: "In einer korrigierten Klausur gab es Abzug für „Lieferant, Abnehmer“ ohne den Zusatz „mit Potenzial zur Vorwärts-/Rückwärtsintegration“.",
    seiten: "Folie 79",
  },
  {
    thema: "mafo", quelle: "Klausur 2024 (offene Frage)",
    frage: "Beschreiben Sie anhand einer Kundenzufriedenheitsanalyse (z. B. Servicebetrieb für Motorräder/Automobile) die grundlegenden Schritte und Aktivitäten dieses Marktforschungsprojekts und begründen Sie das Forschungsdesign. Achtung: Die zentralen Anforderungen der Kunden sind am Beginn noch nicht klar. – Welche Aussagen treffen zu?",
    antworten: [
      { t: "Prozess: Problemdefinition → Informationsquellen → Sekundärdaten ausreichend? → Primärerhebung → Datensammlung → Datenanalyse → Ergebnispräsentation", r: true },
      { t: "Zuerst Sekundärforschung, z. B. Reklamationsstatistik oder Kundendaten (CRM)", r: true },
      { t: "Da die Anforderungen unbekannt sind: zuerst exploratives Design (z. B. Fokusgruppen, Experteninterviews), um die Anforderungen zu ermitteln", r: true },
      { t: "Danach deskriptives Design: standardisierte quantitative Befragung, um die Zufriedenheit zu messen (z. B. ungerade Skala mit 7 oder 9 Stufen)", r: true },
      { t: "Weil die Anforderungen unbekannt sind, eignet sich vor allem ein kausales Design (Experiment)" },
      { t: "Man startet direkt mit einer standardisierten Online-Befragung; die Anforderungen ergeben sich aus den Antworten" },
    ],
    musterantwort: "Problemdefinition (Marketingproblem, Forschungsziel, Informationsbedarf) → Sekundärforschung → Forschungsplan der Primärerhebung (Design, Methode, Instrument, Stichprobe) → Datensammlung → Analyse → Bericht. Exploratives Design ist hypothesenentdeckend (wenig Wissen, erste Einblicke), deskriptives Design hypothesenprüfend (quantitative Messung). Kano-Methode möglich: Vorstudie → funktionale/dysfunktionale Fragen.",
    erklaerung: "Kausales Design untersucht Zusammenhänge (z. B. Werbeaufwand → Absatz) – nicht geeignet, um unbekannte Anforderungen zu finden.",
    seiten: "Folie 105–107, 114–115, 125–126",
  },
  {
    thema: "grund", quelle: "Klausur 2024 (offene Frage)",
    frage: "Welche Aspekte müssen im Rahmen der Planung des Marketing-Programms (= Marketing-Mix) berücksichtigt werden? Beschreiben Sie die vier zentralen Bereiche stichwortartig. – Welche Aussagen treffen zu?",
    antworten: [
      { t: "Leistungspolitik: Produktinnovation, -variation, -differenzierung und -elimination, Produktprogramm", r: true },
      { t: "Preismanagement: preispolitische Ziele/Strategien (z. B. Penetration, Skimming), Preisanalysen, Festsetzung, Durchsetzung, Controlling", r: true },
      { t: "Distribution: Absatzkanalstruktur (direkt/indirekt), Logistik, Unterstützung der Vertriebsorgane", r: true },
      { t: "Kommunikation: Ziele, Auswahl der Instrumente, Budget, Design & Test, Implementierung & Controlling", r: true },
      { t: "Marktforschung ist einer der vier Bereiche des Marketing-Mix" },
      { t: "Personalpolitik ist einer der vier Bereiche des Marketing-Mix" },
    ],
    musterantwort: "4 P: Product (Leistungspolitik), Price (Preismanagement), Place (Distribution), Promotion (Kommunikation). Marktforschung/Informationsversorgung begleitet den ganzen Prozess, ist aber kein Instrument des Marketing-Mix.",
    erklaerung: "In einer korrigierten Klausur gab es Abzüge, wo nur Überschriften genannt wurden – je Bereich Inhalte stichwortartig beschreiben.",
    seiten: "Folie 149–207",
  },
  {
    thema: "grund", quelle: "Klausur WS23 (offene Frage)",
    frage: "Skizzieren Sie den Marketing-Managementprozess und gehen Sie kurz inhaltlich auf die wesentlichen Schritte ein. – Welche Aussagen treffen zu?",
    antworten: [
      { t: "Marketing ist das Leitkonzept, das den gesamten Prozess umspannt", r: true },
      { t: "Die Situationsanalyse umfasst Unternehmensumfeld, Markt/Nachfrager, Mitbewerb, Unternehmen und SWOT", r: true },
      { t: "Auf die Situationsanalyse folgt die strategische Grundausrichtung, danach die Planung des Marketing-Programms", r: true },
      { t: "Die Informationsversorgung (Marktforschung) begleitet alle Phasen des Prozesses", r: true },
      { t: "Die Informationsversorgung findet ausschließlich vor der Situationsanalyse statt" },
      { t: "Der Prozess beginnt mit der Kommunikationspolitik und endet mit der Situationsanalyse" },
    ],
    musterantwort: "Marketing als Leitkonzept → Situationsanalyse (Umfeld, Markt/Nachfrager, Mitbewerb, Unternehmen, SWOT) → strategische Grundausrichtung → Marketing-Programm: nutzenbasierte Leistungspolitik, Preis- & Kostenmanagement, Verkauf/Distribution, Kommunikation; Informationsversorgung über alle Phasen.",
    erklaerung: "Die Grafik mit den Kästen findest du auf Folie 41 (bzw. 51, 100, 142).",
    seiten: "Folie 41, 51",
  },

  // ───────────── Fragen aus dem Skriptum ─────────────
  {
    thema: "grund", quelle: "Skriptum",
    frage: "Welche der folgenden gehören zu den fünf Säulen des Marketing?",
    antworten: [
      { t: "Orientierung an Kundenbedürfnissen", r: true },
      { t: "Zielerreichung durch zufriedene Kunden", r: true },
      { t: "Wettbewerbsorientierung", r: true },
      { t: "Gesellschaftliche Lebensqualität", r: true },
      { t: "Koordiniertes Marketing", r: true },
      { t: "Maximierung des Werbebudgets" },
    ],
    musterantwort: "Die fünf Säulen: Orientierung an Kundenbedürfnissen, Zielerreichung durch zufriedene Kunden, Wettbewerbsorientierung, gesellschaftliche Lebensqualität, koordiniertes Marketing.",
    erklaerung: "Das Dach ist „Marketing“ – ohne eine der Säulen ist es nicht stabil.",
    seiten: "Folie 14",
  },
  {
    thema: "grund", quelle: "Skriptum",
    frage: "Welche Aussagen zum Marketingkonzept (in Anlehnung an Kotler) treffen zu?",
    antworten: [
      { t: "Die Aufgabe besteht darin, die Bedürfnisse der Zielmärkte zu ermitteln", r: true },
      { t: "Die Befriedigung soll wirkungsvoller und wirtschaftlicher erfolgen als durch die Wettbewerber", r: true },
      { t: "Die Lebensqualität der Gesellschaft soll dabei bewahrt oder verbessert werden", r: true },
      { t: "Marketing ist eine separate Abteilung, die unabhängig von anderen Unternehmensbereichen arbeitet" },
    ],
    musterantwort: "Marketingkonzept: Bedürfnisse der Zielmärkte ermitteln und die gewünschten Befriedigungswerte wirkungsvoller und wirtschaftlicher erfüllen als die Wettbewerber – auf eine Weise, die die Lebensqualität der Gesellschaft bewahrt oder verbessert.",
    erklaerung: "Peter Drucker: Marketing darf man nicht als separate betriebliche Funktion sehen – es umfasst das gesamte Unternehmen vom Standpunkt des Kunden.",
    seiten: "Folie 12, 39–40",
  },
  {
    thema: "grund", quelle: "Skriptum",
    frage: "Welche Aussagen zur Wertkette von Porter im Zusammenhang mit Kundenbedürfnissen treffen zu?",
    antworten: [
      { t: "Viele Bereiche im Unternehmen können direkt oder indirekt zur Nutzensteigerung für den Kunden beitragen", r: true },
      { t: "Primäre Aktivitäten sind z. B. Eingangslogistik, Produktion, Ausgangslogistik, Kommunikation & Vertrieb, Kundendienst", r: true },
      { t: "Sekundäre Aktivitäten sind z. B. Unternehmensinfrastruktur, Personalmanagement, F&E, Beschaffung", r: true },
      { t: "Nur der Vertrieb kann zur Steigerung des Kundennutzens beitragen" },
    ],
    musterantwort: "Wertkette: primäre Aktivitäten (Eingangslogistik, Produktion, Ausgangslogistik, Kommunikation & Vertrieb, Kundendienst) und sekundäre (Infrastruktur, Personal, F&E, Beschaffung) – z. B. alle tragen zum Kundenwert „hervorragende Produktqualität“ bei.",
    erklaerung: "Die Wertkette ist auch Ausgangspunkt der Fähigkeitenanalyse von Wettbewerbern.",
    seiten: "Folie 19–20, 83",
  },
  {
    thema: "grund", quelle: "Skriptum",
    frage: "Welche Aussagen zu Wertgewinn, Nettonutzendifferenz und komparativem Konkurrenzvorteil (KKV) treffen zu?",
    antworten: [
      { t: "Ein Wertgewinn für den Abnehmer ist notwendige Bedingung, damit ein Angebot überhaupt als kaufrelevant betrachtet wird", r: true },
      { t: "Die Nettonutzendifferenz zum Mitbewerber ist entscheidend für das Bestehen im Wettbewerb", r: true },
      { t: "Ein KKV liegt vor, wenn sowohl ein relativer Vorteil aus Kundensicht als auch ein ökonomischer Vorteil für den Anbieter erreicht wird", r: true },
      { t: "Für einen KKV genügt es, dem Kunden den höchsten Nettonutzen zu bieten – der eigene ökonomische Vorteil ist unerheblich" },
    ],
    musterantwort: "Kunde entscheidet sich für das Angebot mit dem höchsten Nettonutzen. Neben der Nettonutzendifferenz muss auch der daraus resultierende ökonomische Vorteil für das Unternehmen („Wert für Anbieter“) erreicht werden – dann besteht ein komparativer Konkurrenzvorteil.",
    erklaerung: "Die Bestimmungsfaktoren eines Wettbewerbsvorteils: Bedürfnisse der Nachfrager, Problemlösungs-Know-how des Anbieters und des Konkurrenten (Analyse relativer Positionen).",
    seiten: "Folie 32–36",
  },
  {
    thema: "grund", quelle: "Skriptum",
    frage: "Welche Aussagen zur Kano-Methode (Vorgehensweise und Auswertung) treffen zu?",
    antworten: [
      { t: "Kundenanforderungen werden zunächst mittels Vorstudie (z. B. Fokusgruppen, qualitative Befragung) identifiziert", r: true },
      { t: "Für jede Anforderung werden zwei Fragen gestellt: eine funktionale (positiv) und eine dysfunktionale (negativ)", r: true },
      { t: "Am besten eignen sich standardisierte mündliche Interviews", r: true },
      { t: "Die Auswertung kennt u. a. die Kategorien Attractive, Must-be, One-dimensional, Indifferent, Reverse und Questionable", r: true },
      { t: "Jede Anforderung wird mit genau einer offenen Frage abgefragt" },
    ],
    musterantwort: "1. Identifikation der Anforderungen (Vorstudie) 2. Fragebogen: je Anforderung funktionale und dysfunktionale Frage 3. standardisierte mündliche Interviews 4. Auswertung laut Tabelle: Attractive = Begeisterung, Must-be = Basis, One-dimensional = Leistung, dazu Indifferent, Reverse, Questionable.",
    erklaerung: "Ziele: Einfluss der Anforderungen auf die Zufriedenheit abschätzen, maßgeschneiderte Leistungspakete, Prioritäten für die Produktentwicklung.",
    seiten: "Folie 25, 29–31",
  },
  {
    thema: "grund", quelle: "Skriptum",
    frage: "Welche Aussagen zu Kundenstrategien treffen zu?",
    antworten: [
      { t: "Man unterscheidet die offensive Strategie „Neue Kunden gewinnen“ und die defensive Strategie „Bestehende Kunden binden“", r: true },
      { t: "Kundenzufriedenheit ist Basis für den Erfolg, aber nicht alles", r: true },
      { t: "Bestehende Kunden zu binden ist die offensive Kundenstrategie" },
      { t: "Kundenzufriedenheit garantiert automatisch den Unternehmenserfolg" },
    ],
    musterantwort: "Kundenstrategien: neue Kunden gewinnen (offensiv) vs. bestehende Kunden binden (defensiv). Kundenzufriedenheit ist Basis für den Erfolg – aber nicht alles.",
    erklaerung: "Im Skriptum wird gefragt: „Welche Strategie ist günstiger?“ – das Binden bestehender Kunden setzt Zufriedenheit voraus.",
    seiten: "Folie 21, 24",
  },
  {
    thema: "b2b", quelle: "Skriptum",
    frage: "Welche Merkmale unterscheiden B2B-Märkte typischerweise von B2C-Märkten?",
    antworten: [
      { t: "Abgeleitete Nachfrage statt originärer Nachfrage", r: true },
      { t: "Organisationen statt Menschen als Nachfrager", r: true },
      { t: "Formalisierter Bedarf, z. B. mit Ausschreibungen", r: true },
      { t: "Hohe Individualisierung und hohe Interaktion", r: true },
      { t: "Typischerweise entscheidet eine einzelne Person" },
    ],
    musterantwort: "B2C → B2B: originäre → abgeleitete Nachfrage (Multilevel Marketing); Menschen → Organisationen (Einkaufsrichtlinien); eine Person → mehrere Personen (Team Selling); nicht formalisiert → formalisierter Bedarf (Ausschreibungen); geringe → hohe Individualisierung (Co-Development); geringe → hohe Interaktion (Key Account Management).",
    erklaerung: "Die rechte Spalte der Tabelle nennt jeweils die Implikation für das B2B-Marketing.",
    seiten: "Folie 48",
  },
  {
    thema: "b2b", quelle: "Skriptum",
    frage: "Wie unterscheiden sich Industriegütermarketing und B2B-Marketing laut Skriptum?",
    antworten: [
      { t: "Industriegütermarketing schließt die Vermarktung an Institutionen der reinen Distribution an Letztkonsumenten (Handel) aus", r: true },
      { t: "B2B-Marketing umfasst auch die Vermarktung an reine Distributoren (Handel)", r: true },
      { t: "Industriegüter können auch Dienstleistungen sein", r: true },
      { t: "Industriegütermarketing und B2B-Marketing sind vollkommen deckungsgleich" },
    ],
    musterantwort: "Industriegüter definieren sich über den Abnehmer (Organisationen) und können Dienstleistungen sein. Industriegütermarketing fokussiert Industrieunternehmen, die selbst Leistungen herstellen, und schließt den Handel aus; B2B-Marketing schließt den Handel ein.",
    erklaerung: "Merke: B2B ist der weitere Begriff.",
    seiten: "Folie 45",
  },
  {
    thema: "sit", quelle: "Skriptum",
    frage: "Welche Aussagen zur Situationsanalyse treffen zu?",
    antworten: [
      { t: "Jede Marketingentscheidung hängt von der eigenen Lage und der Unternehmensumwelt ab", r: true },
      { t: "Die Umfeldanalyse ergibt Chancen und Risiken, die Unternehmensanalyse Stärken und Schwächen", r: true },
      { t: "Es sind jeweils jene Variablen zu analysieren, die für die Entscheidungssituation relevant sind", r: true },
      { t: "Ihre Bedeutung wird in der Praxis häufig überschätzt, weil Unternehmen ihre Kunden ohnehin genau kennen" },
    ],
    musterantwort: "Bestimmung der strategischen Ist-Situation mit Umfeldanalyse (Chancen/Risiken) und Unternehmensanalyse (Stärken/Schwächen). Aus der Gesamtheit möglicher Variablen die relevanten analysieren. Die Bedeutung einer differenzierten Situationsanalyse wird häufig unterschätzt („wir wissen doch genau, was Kunden wollen!“).",
    erklaerung: "Veränderungen des Status quo können Risiko (verhindern) oder Chance (verstärken, nutzen) sein.",
    seiten: "Folie 52–53, 56",
  },
  {
    thema: "sit", quelle: "Skriptum",
    frage: "Welche Informationsfelder gehören zum Mikroumfeld eines Unternehmens?",
    antworten: [
      { t: "Kunden", r: true },
      { t: "Mitbewerber", r: true },
      { t: "Markt", r: true },
      { t: "Ökologie, Ökonomie, Recht, Technologie und Gesellschaft" },
    ],
    musterantwort: "Mikroumfeld: Markt mit Kunden, Unternehmen und Mitbewerbern (Kundennutzen, Wettbewerbsvorteil). Makroumfeld (Umwelt): Ökologie, Ökonomie, Recht, Technologie, Gesellschaft – analysiert mit PESTEL.",
    erklaerung: "Grafik mit den zwei Ellipsen: außen Makroumfeld, innen Mikroumfeld.",
    seiten: "Folie 57",
  },
  {
    thema: "sit", quelle: "Skriptum",
    frage: "Welche Aussagen zu Porters Five Forces treffen zu?",
    antworten: [
      { t: "Das Modell analysiert die Attraktivität und Wettbewerbsintensität einer Branche", r: true },
      { t: "Die Kräfte sind: Rivalität in der Branche, Gefahr durch neue Wettbewerber, Gefahr durch Substitutionsprodukte, Verhandlungsmacht der Lieferanten und der Abnehmer", r: true },
      { t: "Eintrittsbarrieren sind z. B. Economies of Scale, Markenbindung, Kapitalbedarf, Wechselkosten", r: true },
      { t: "Five Forces ist das zentrale Tool der Makro-Umfeldanalyse" },
    ],
    musterantwort: "Five Forces (Mikro-Umfeld): Ziel ist zu verstehen, wo Gewinnpotenziale entstehen bzw. unter Druck geraten. Rivalität hängt u. a. von Anzahl der Wettbewerber, Branchenwachstum, Überkapazitäten, Austrittsbarrieren, Produktdifferenzierung ab.",
    erklaerung: "Five Forces hilft auch, die relevanten (auch potenziellen) Konkurrenten zu bestimmen.",
    seiten: "Folie 68–69, 79",
  },
  {
    thema: "sit", quelle: "Skriptum",
    frage: "Welche Rollen im Buying Center sind richtig beschrieben (nach Webster & Wind)?",
    antworten: [
      { t: "Decider: entscheidet aufgrund seiner Autorität letztgültig über den Kaufprozess", r: true },
      { t: "Buyer: verantwortet formal den Kaufprozess", r: true },
      { t: "Influencer: beeinflusst den Kaufprozess in vielfältiger Weise (z. B. Berater)", r: true },
      { t: "Gatekeeper: repräsentiert die Anwendergruppe der zu kaufenden Leistung" },
    ],
    musterantwort: "User: Anwendergruppe · Influencer: beeinflusst (z. B. Berater) · Buyer: verantwortet formal den Kauf · Decider: entscheidet letztgültig · Gatekeeper: selektiert und verteilt Informationen, Termine (z. B. Assistent).",
    erklaerung: "Die Anwendergruppe ist der User, nicht der Gatekeeper.",
    seiten: "Folie 72",
  },
  {
    thema: "sit", quelle: "Skriptum",
    frage: "Welche Definitionen der quantitativen Marktgrößen sind richtig?",
    antworten: [
      { t: "Marktpotenzial: maximal mögliche Absatzmenge / Umsatz in einem Markt (Aufnahmefähigkeit)", r: true },
      { t: "Marktvolumen: Gesamtheit der realisierten Absatzmengen / Umsatz einer Branche", r: true },
      { t: "Absatzvolumen: Gesamtheit der realisierten eigenen Absatzmengen / Umsatz", r: true },
      { t: "Absatzpotenzial: tatsächlich realisierter Umsatz der gesamten Branche" },
    ],
    musterantwort: "Effektiv/potenziell × unternehmens-/marktbezogen: Absatzvolumen (eigene realisierte Menge), Absatzpotenzial (maximal mögliche eigene Menge), Marktvolumen (realisierte Menge der Branche), Marktpotenzial (maximal mögliche Menge im Markt).",
    erklaerung: "Absatzpotenzial = maximal mögliche Absatzmenge eines Unternehmens.",
    seiten: "Folie 74–75",
  },
  {
    thema: "sit", quelle: "Skriptum (Rechenbeispiel)",
    frage: "Ein Chemiebetrieb setzt jährlich 6,3 Mio. Liter Reinigungsmittel ab. Maximal können 140 Mio. Liter verkauft werden; die Branche deckt aktuell 85 % davon ab; Ziel des Herstellers sind 10 % des Maximums. Welche Werte stimmen?",
    antworten: [
      { t: "Marktpotenzial = 140 Mio. Liter", r: true },
      { t: "Marktvolumen = 119 Mio. Liter", r: true },
      { t: "Absatzpotenzial = 14 Mio. Liter", r: true },
      { t: "Marktanteil ≈ 5,3 %", r: true },
      { t: "Marktanteil = 4,5 %" },
    ],
    musterantwort: "Marktpotenzial 140 Mio. L; Marktvolumen = 0,85 · 140 = 119 Mio. L; Absatzpotenzial = 0,10 · 140 = 14 Mio. L; Absatzvolumen = 6,3 Mio. L; Marktanteil = 6,3 / 119 · 100 ≈ 5,3 %.",
    erklaerung: "4,5 % wären 6,3 / 140 – der Marktanteil bezieht sich aber auf das Marktvolumen, nicht auf das Marktpotenzial.",
    seiten: "Folie 75–76",
  },
  {
    thema: "sit", quelle: "Skriptum",
    frage: "Welche Aussagen zur Vorgehensweise bei der Wettbewerbsanalyse treffen zu?",
    antworten: [
      { t: "Zuerst werden die relevanten Konkurrenten bestimmt", r: true },
      { t: "Analysiert werden bisher verfolgte Strategie, Ziele, Fähigkeiten/Ressourcen der Konkurrenten und die Umwelt", r: true },
      { t: "Ergebnis ist ein zusammenfassendes Konkurrenz-Reaktionsprofil", r: true },
      { t: "Die Analyse vergleicht die Konkurrenten ausschließlich untereinander, ohne Bezug zur eigenen Position" },
    ],
    musterantwort: "a) relevante Konkurrenten bestimmen b) relative Konkurrenzanalyse: 1. Strategie 2. Ziele 3. Fähigkeiten/Ressourcen (Wertkette) 4. Umwelt c) Konkurrenz-Reaktionsprofil. Ziel: eigene Position im Vergleich zu den relevanten Mitbewerbern und erwartbare Konkurrenzmaßnahmen.",
    erklaerung: "Die Analyse hat immer im Vergleich der eigenen Position zu der der relevanten Konkurrenten zu erfolgen.",
    seiten: "Folie 77–84",
  },
  {
    thema: "sit", quelle: "Skriptum",
    frage: "Wie werden Chancen und Risiken nach der Umfeldanalyse bewertet?",
    antworten: [
      { t: "Chancen nach Erfolgspotenzial und Eintrittswahrscheinlichkeit", r: true },
      { t: "Risiken nach Gefährdungspotenzial und Eintrittswahrscheinlichkeit", r: true },
      { t: "Höchst relevante Chancen und Risiken müssen unbedingt in der weiteren Planung berücksichtigt werden", r: true },
      { t: "Nach Umsatzanteil und Deckungsbeitrag der betroffenen Produkte" },
    ],
    musterantwort: "Ergebnisse der Makro- und Mikroanalyse werden als Chance oder Risiko klassifiziert und in einer Matrix (Potenzial × Wahrscheinlichkeit, Quadranten Q1–Q4) bewertet. Beispiel Automobilzulieferer: Fahrverbot in Stadtzentren = Risiko.",
    erklaerung: "Manche Entwicklungen sind Chance und Risiko zugleich (z. B. Klimawende für Verbrennungsmotor-Zulieferer).",
    seiten: "Folie 85–86",
  },
  {
    thema: "sit", quelle: "Skriptum",
    frage: "Welche Schritte gehören zur Stärken-Schwächen-Analyse (Unternehmensanalyse)?",
    antworten: [
      { t: "Identifikation erfolgskritischer Faktoren („key success factors“)", r: true },
      { t: "Erstellung einer Checkliste und Bewertung nach Leistungsausprägung und Wichtigkeit", r: true },
      { t: "Bewertung des Mitbewerbs und Darstellung als Stärken-Schwächen-Profil", r: true },
      { t: "Klassifizierung von PESTEL-Trends in Chancen und Risiken" },
    ],
    musterantwort: "Warum: Das Unternehmen muss über die notwendigen Fähigkeiten verfügen, um Chancen wahrzunehmen. Vorgehen: Erfolgsfaktoren → Checkliste → Bewertung (Experten, Hard Facts) → Bewertung Mitbewerb → Stärken-Schwächen-Profil.",
    erklaerung: "Die Klassifizierung in Chancen/Risiken gehört zur Umfeldanalyse.",
    seiten: "Folie 88–90",
  },
  {
    thema: "sit", quelle: "Skriptum",
    frage: "Welche Aussagen zur SWOT-Analyse / TOWS-Matrix treffen zu?",
    antworten: [
      { t: "Sie verbindet die Stärken-Schwächen-Analyse mit der Chancen-Risiken-Analyse", r: true },
      { t: "Vorgehen: Katalogisieren → Gegenüberstellen in der TOWS-Matrix → Handlungsoptionen ableiten", r: true },
      { t: "Leitfrage S-O: Wie kann ich eine Stärke einsetzen, um von einer Chance zu profitieren?", r: true },
      { t: "Leitfrage W-T: Was muss ich tun, um trotz Schwäche das Risiko zu minimieren?", r: true },
      { t: "Die SWOT-Analyse ersetzt die Umfeld- und Unternehmensanalyse" },
    ],
    musterantwort: "SWOT = analysenbasierte Ableitung strategischer Handlungsoptionen: 1. Katalogisierung/Systematisierung 2. Gegenüberstellung interner S/W mit externen O/T 3. Handlungsoptionen je Feld (S-O, W-O, S-T, W-T). Beispiel BMW AG.",
    erklaerung: "Die SWOT baut auf den Ergebnissen von Umfeld- und Unternehmensanalyse auf – sie ersetzt sie nicht.",
    seiten: "Folie 91–97",
  },
  {
    thema: "mafo", quelle: "Skriptum",
    frage: "Welche Aussagen zum Marketingforschungsprozess treffen zu?",
    antworten: [
      { t: "Die Problemdefinition umfasst Marketingproblem, Forschungsziel und Informationsbedarf", r: true },
      { t: "Sind die Sekundärdaten ausreichend, kann direkt zur Datenanalyse übergegangen werden", r: true },
      { t: "Der Forschungsplan der Primärerhebung umfasst Forschungsdesign, -methode, -instrument und Stichprobendefinition", r: true },
      { t: "Die Primärerhebung steht immer am Beginn, die Sekundärforschung wird nur bei Bedarf angehängt" },
    ],
    musterantwort: "Entscheidung Projekt → Problemdefinition → Informationsquellen → Sekundärdaten ausreichend? (ja → Datenanalyse; nein → Primärerhebung mit Forschungsplan) → Datensammlung → Datenanalyse → Ergebnispräsentation.",
    erklaerung: "Sekundärforschung sollte immer am Beginn eines Marketingforschungsprojekts stehen.",
    seiten: "Folie 105–107",
  },
  {
    thema: "mafo", quelle: "Skriptum",
    frage: "Welche Quellen der Sekundärforschung sind betriebsintern?",
    antworten: [
      { t: "Umsatz-, Absatz- und Vertriebsstatistik", r: true },
      { t: "Reklamationsstatistik", r: true },
      { t: "Kostenrechnung sowie Kundendaten/CRM", r: true },
      { t: "Veröffentlichungen der Wirtschaftskammer und Patentämter" },
    ],
    musterantwort: "Intern: Umsatz-/Absatz-/Vertriebsstatistik, Reklamationsstatistik, Kostenrechnung, CRM. Extern: Veröffentlichungen (BMWA, WK), Fachbücher/-zeitschriften, Firmenveröffentlichungen, Patentämter, Universitätsstudien, Statistikämter.",
    erklaerung: "WK und Patentämter sind betriebsexterne Quellen.",
    seiten: "Folie 108–110",
  },
  {
    thema: "mafo", quelle: "Skriptum",
    frage: "Welche Aussagen zu den grundsätzlichen Forschungsdesigns der Primärforschung treffen zu?",
    antworten: [
      { t: "Exploratives Design: wenig Wissen vorhanden, erste Einblicke, hypothesenentdeckend (z. B. Fokusgruppen, Expertengespräche)", r: true },
      { t: "Deskriptives Design: Problem bereits präzisiert, quantitative Messung, hypothesenprüfend", r: true },
      { t: "Kausales Design: Zusammenhänge und Abhängigkeiten untersuchen (z. B. Werbeaufwand – Absatz), Achtung auf Scheinkausalitäten", r: true },
      { t: "Exploratives Design ist hypothesenprüfend und arbeitet vor allem mit großen quantitativen Befragungen" },
    ],
    musterantwort: "Explorativ (hypothesenentdeckend, qualitativ), deskriptiv (hypothesenprüfend, quantitative Befragungen), kausal (hypothesenprüfend, Experimente, multivariate Analysen).",
    erklaerung: "Merke: nur das explorative Design ist hypothesenentdeckend.",
    seiten: "Folie 114–115",
  },
  {
    thema: "mafo", quelle: "Skriptum",
    frage: "Welche Aussagen zu Beobachtung und Experiment treffen zu?",
    antworten: [
      { t: "Beobachtung ist die systematische Erfassung sinnlich wahrnehmbarer Sachverhalte durch Personen oder technische Hilfsmittel", r: true },
      { t: "Typische Anwendungen der Beobachtung sind z. B. Produkttests, Kundenlaufstudien oder Eye-Tracking", r: true },
      { t: "Ein Experiment ist eine wiederholbare Versuchsanordnung zur empirischen Überprüfung von Hypothesen unter kontrollierten Bedingungen", r: true },
      { t: "Bei einer Beobachtung geben Personen über bestimmte Sachverhalte selbst Auskunft" },
    ],
    musterantwort: "Erhebungsmethoden: Beobachtung, Befragung (qualitativ/quantitativ), Sonderform Experiment (Produkt-, Store-, Markttest, Werbeforschung; z. B. Blindtest vs. identifizierter Test).",
    erklaerung: "„Personen geben Auskunft“ ist die Befragung.",
    seiten: "Folie 116–120, 127–128",
  },
  {
    thema: "mafo", quelle: "Skriptum",
    frage: "Welche Empfehlungen zur Fragebogengestaltung gibt das Skriptum?",
    antworten: [
      { t: "Fragen sollen neutral, eindeutig und zielgruppengerecht formuliert sein; sensible Fragen eher indirekt", r: true },
      { t: "Die Skala sollte ungerade sein, ideal ist eine Linienskala mit 7 oder 9 Abstufungen", r: true },
      { t: "Reihenfolge: Einleitung → Filter-/Screeningfragen → Eisbrecher → Themenfragen → Kontrollfragen → Demografie", r: true },
      { t: "Grafische Skalen (z. B. Smileys) und durchgehend verbal beschriftete Skalen sind für Erwachsene besonders zu empfehlen" },
    ],
    musterantwort: "Grundsätze: neutral („Wie zufrieden…“ statt „Wie begeistert…“), eindeutig, zielgruppengerecht, sensible Fragen indirekt. Skalen: ungerade, 7 oder 9 Stufen, keine grafische Unterstützung (außer Gesichterskala bei Kleinkindern), verbal nur die Extrempositionen. Themenfragen vom Einfachen zum Speziellen.",
    erklaerung: "Skalenarten: reines Kontinuum, monopolar, monopolar mit grafischer Unterstützung, bipolar, Flächenskala.",
    seiten: "Folie 122, 124–126",
  },
  {
    thema: "mafo", quelle: "Skriptum",
    frage: "Welche Aussagen zu geschlossenen Fragen treffen zu?",
    antworten: [
      { t: "Sie sind weniger abhängig vom Ausdrucksvermögen der Befragten", r: true },
      { t: "Datensammlung, -aufzeichnung und -aufbereitung sind weniger zeitaufwändig", r: true },
      { t: "Sie sind weniger geeignet für explorative Fragestellungen und liefern keine tiefergehenden Antworten", r: true },
      { t: "Die Entwicklung geschlossener Fragen ist immer weniger aufwändig als die offener Fragen" },
    ],
    musterantwort: "Vorteile: mehr Themen abhandelbar, weniger Zeit, geringere Kosten, geringere Fehlerrate, geringere Belastung. Nachteile: wenig explorativ, u. U. höherer Aufwand bei der Fragenentwicklung, keine Garantie, dass Antworten die Meinung vollständig wiedergeben.",
    erklaerung: "Die Fragenentwicklung kann bei geschlossenen Fragen sogar aufwändiger sein.",
    seiten: "Folie 123",
  },
  {
    thema: "mafo", quelle: "Skriptum",
    frage: "Welche Auswahlverfahren für Stichproben sind richtig beschrieben?",
    antworten: [
      { t: "Einfache Zufallsauswahl: jedes Element hat die gleiche Wahrscheinlichkeit; die Grundgesamtheit muss vollständig bekannt sein", r: true },
      { t: "Geschichtete Zufallsauswahl: aus jeder Gruppe (z. B. PKW-, SUV-, Nutzfahrzeugkunden) wird zufällig ausgewählt", r: true },
      { t: "Klumpenauswahl: einige Gruppen (z. B. 2 von 15 Filialen) werden zufällig gewählt und dort alle befragt", r: true },
      { t: "Snowball Sampling: Befragte nennen weitere Personen mit den gleichen Merkmalen", r: true },
      { t: "Quotenverfahren: basiert auf dem Zufallsprinzip und braucht keine Kenntnis der Merkmale der Grundgesamtheit" },
    ],
    musterantwort: "Einfache Zufallsauswahl erlaubt mathematisch-statistisch fundierte Fehlerberechnung. Das Quotenverfahren braucht nicht das Zufallsprinzip, sondern die Kenntnis der relevanten Merkmale (Quoten) der Grundgesamtheit. Snowball Sampling verringert „Leerinterviews“.",
    erklaerung: "Bei der Klumpenauswahl auf den Klumpeneffekt achten.",
    seiten: "Folie 130–134",
  },
  {
    thema: "mafo", quelle: "Skriptum",
    frage: "Welche typischen Informationsbedarfe deckt die Marktforschung ab?",
    antworten: [
      { t: "Identifizierung relevanter Trends („schwache Signale“)", r: true },
      { t: "Marktsegmentierung, Zielgruppendefinition und Buying-Center-Analyse", r: true },
      { t: "Kundenzufriedenheit, Wettbewerbsaktivitäten, Preisgestaltung, Testkäufe (Mystery Shopping)", r: true },
      { t: "Erstellung der Buchhaltung und Lohnverrechnung" },
    ],
    musterantwort: "Trends, Segmentierung, Buying Center, Kundenbedürfnisse, Anwenderverhalten, Zufriedenheit/Loyalität, Wettbewerb, Wahrnehmung von Produkt/Service/Image, Produktentwicklung/-tests, Preisgestaltung, Testkäufe. Datenerhebung allein reicht nicht – Insights sind der Schlüssel.",
    erklaerung: "Präsentation & Bericht: zielgruppenspezifisch, nicht zu lang, keine „Zahlenfriedhöfe“.",
    seiten: "Folie 103, 138",
  },
  {
    thema: "strat", quelle: "Skriptum",
    frage: "Welche Merkmale kennzeichnen die Kostenführerschaft laut Porter?",
    antworten: [
      { t: "Breites Sortiment zu niedrigen Preisen", r: true },
      { t: "Hohe Marktanteile und Erfahrungskurveneffekte", r: true },
      { t: "Effiziente Produktion ist notwendig („gutes Standardprodukt“)", r: true },
      { t: "Einzigartigkeit durch Image und Innovation mit hohem preispolitischem Spielraum" },
    ],
    musterantwort: "Kostenführer: breites Sortiment, niedrige Preise, hohe Marktanteile, Erfahrungskurve, effiziente Produktion. Differenzierer: Einzigartigkeit (außer Preis), höherer Preisspielraum – Zusatzgewinn, wenn der Mehrpreis die Zusatzkosten übersteigt.",
    erklaerung: "Die letzte Aussage beschreibt die Differenzierung.",
    seiten: "Folie 146–147",
  },
  {
    thema: "leist", quelle: "Skriptum",
    frage: "Welche Entscheidungstatbestände der Leistungspolitik sind richtig definiert?",
    antworten: [
      { t: "Produktinnovation: Prozesse zur Entwicklung von Neuprodukten", r: true },
      { t: "Produktvariation: Veränderung von bereits im Markt eingeführten Produkten", r: true },
      { t: "Produktdifferenzierung: zeitlich paralleles Angebot mehrerer Produktvarianten", r: true },
      { t: "Produktelimination: Produkte werden vom Markt genommen", r: true },
      { t: "Produktstandardisierung: Ausweitung der Angebotsbreite" },
    ],
    musterantwort: "Innovation, Variation, Differenzierung (Varianten) bzw. Standardisierung (Reduktion der Angebotsbreite), Elimination – je nach Phase im Produktlebenszyklus (Einführung, Wachstum, Reife, Rückgang).",
    erklaerung: "Standardisierung = Reduktion der Angebotsbreite, nicht Ausweitung.",
    seiten: "Folie 153–154",
  },
  {
    thema: "leist", quelle: "Skriptum",
    frage: "Wann ist eine Produktvariation notwendig?",
    antworten: [
      { t: "Wenn sich die Position der Nachfrager im Produkt-Marktfeld verändert hat", r: true },
      { t: "Bei technischem Fortschritt oder neuen gesetzlichen Vorschriften", r: true },
      { t: "Wenn Konkurrenten verbesserte Produkte launchen oder der Umsatz stagniert", r: true },
      { t: "Nur dann, wenn das Produkt komplett vom Markt genommen werden soll" },
    ],
    musterantwort: "Anlässe: veränderte Nachfragerposition, Produkt deckt sich nicht mit Soll-Position („Kinderkrankheiten“), Imageänderung (z. B. Diesel), technischer Fortschritt/Gesetze, verbesserte Konkurrenzprodukte, stagnierender Umsatz (Relaunch). Ansatzpunkte: physikalische/funktionale Eigenschaften, Ästhetik, Marke, Services.",
    erklaerung: "Vom Markt nehmen = Produktelimination.",
    seiten: "Folie 155",
  },
  {
    thema: "leist", quelle: "Skriptum",
    frage: "Welche Aussagen zur BCG-Matrix treffen zu?",
    antworten: [
      { t: "Stars haben hohes Marktwachstum und hohen relativen Marktanteil", r: true },
      { t: "Cash Cows haben geringes Marktwachstum und hohen relativen Marktanteil", r: true },
      { t: "Question Marks haben hohes Marktwachstum, aber geringen relativen Marktanteil", r: true },
      { t: "Poor Dogs haben hohes Marktwachstum und geringen relativen Marktanteil" },
    ],
    musterantwort: "Achsen: relativer Marktanteil (0,1 – 1 – 10) und Marktwachstum. Question Mark (hoch/gering), Star (hoch/hoch), Cash Cow (gering/hoch), Poor Dog (gering/gering). Idealer Weg: Question Mark → Star → Cash Cow. Längsschnittanalysen (Ist t, Ist t+1, Plan) für das Produktcontrolling.",
    erklaerung: "Poor Dogs: geringes Wachstum UND geringer relativer Marktanteil.",
    seiten: "Folie 162–164",
  },
  {
    thema: "leist", quelle: "Skriptum",
    frage: "Welche Analysen unterstützen die Planung des Produktprogramms?",
    antworten: [
      { t: "Altersstrukturanalysen (Restlebenserwartung und Umsatzbeitrag der Produkte)", r: true },
      { t: "Umsatzstrukturanalysen (Anteil am Umsatz, beanspruchte Produktionskapazität)", r: true },
      { t: "Portfolioanalysen wie die BCG-Matrix sowie Umsatz- und Deckungsbeitragsanalysen", r: true },
      { t: "Eine einzige Kennzahl, nämlich der kurzfristige Umsatz jedes Produkts" },
    ],
    musterantwort: "Produktsortiment = Gesamtheit aller Produktlinien und Artikel (Breite und Tiefe). Fundierte Entscheidungen verbinden Alters-, Umsatz-, Ertrags-, Kundenstruktur, Marktanteile, Marktwachstum, Deckungsbeiträge u. a.",
    erklaerung: "Fazit im Skriptum: mehr als Einzelprodukte oder kurzfristige Umsatzentwicklung betrachten.",
    seiten: "Folie 158–167",
  },
  {
    thema: "leist", quelle: "Skriptum",
    frage: "Wofür liefern Positionierungsanalysen wertvolle Hinweise?",
    antworten: [
      { t: "Für die Leistungspolitik", r: true },
      { t: "Für die Preispolitik (z. B. Prämienpreise vs. Promotionspreise)", r: true },
      { t: "Für die Kommunikationspolitik (Botschaft, Medienselektion)", r: true },
      { t: "Für die Distributionspolitik (direkter vs. indirekter Vertrieb, Absatzpartner)", r: true },
    ],
    musterantwort: "Die Positionierungsanalyse (Wahrnehmung alt/neu, Marktsegmente) liefert Infos für den gesamten Marketing-Mix: Produkt, Preis, Place, Promotion.",
    erklaerung: "Alle vier Antworten sind richtig.",
    seiten: "Folie 156–157",
  },
  {
    thema: "preis", quelle: "Skriptum (Rechenbeispiel)",
    frage: "Preis 100 €, variable Stückkosten 60 €, Absatz 1 Mio. Stück, Fixkosten 30 Mio. €. Der Vertrieb will den Preis um 5 % senken, sonst sinkt die Menge um 5 %. Welche Aussagen stimmen?",
    antworten: [
      { t: "Ausgangsgewinn: 10 Mio. €", r: true },
      { t: "5 % Preissenkung → Gewinn 5 Mio. € (−50 %)", r: true },
      { t: "5 % weniger Menge → Gewinn 8 Mio. € (−20 %)", r: true },
      { t: "Beide Varianten verringern den Gewinn um jeweils 5 %" },
    ],
    musterantwort: "Ausgang: DB 40 € · 1 Mio. = 40 Mio. − 30 Mio. = 10 Mio. Preis 95 €: DB 35 € · 1 Mio. = 35 Mio. − 30 Mio. = 5 Mio. (−50 %). Menge 950.000: 40 € · 950.000 = 38 Mio. − 30 Mio. = 8 Mio. (−20 %). → Der Preis ist ein sehr starker Gewinnhebel.",
    erklaerung: "Zusätzlich zu beachten: Reaktionen der Wettbewerber, Preisimage, Kundenbeziehung.",
    seiten: "Folie 169–170",
  },
  {
    thema: "preis", quelle: "Skriptum",
    frage: "Welche Aussagen zu Penetrations- und Skimmingstrategie treffen zu?",
    antworten: [
      { t: "Penetration: schnelle Erschließung von Massenmärkten mit relativ niedrigen Preisen – Gefahr eines negativen Produktimages", r: true },
      { t: "Skimming: hoher Einführungspreis, der sukzessive gesenkt wird – Ziel schnelle Amortisation der Investitionen", r: true },
      { t: "Skimming empfiehlt sich bei Käufern mit ausgeprägtem Bedürfnis und Zahlungswillen und geringer Substituierbarkeit", r: true },
      { t: "Penetration empfiehlt sich vor allem bei geringer Preissensibilität der Kunden" },
    ],
    musterantwort: "Penetration: rasche Diffusion; empfehlenswert bei hoher Preissensibilität, sinkenden Kosten durch Erfahrung, Abschrecken der Konkurrenz. Skimming: bei eher kurzen Lebenszyklen und Einzigartigkeit; empfehlenswert bei hoher Zahlungsbereitschaft, zur Unterstützung der Positionierung, wenn wenige Konkurrenten angelockt werden.",
    erklaerung: "Penetration passt zu HOHER Preissensibilität.",
    seiten: "Folie 174–175",
  },
  {
    thema: "preis", quelle: "Skriptum",
    frage: "Welche Aussagen zur kostenorientierten und nutzenorientierten Preisbildung treffen zu?",
    antworten: [
      { t: "Kosten-Plus-Preisbildung ist wegen ihrer Anwendungsfreundlichkeit v. a. im Industriegüterbereich weit verbreitet", r: true },
      { t: "Kosteninformationen sind wichtig für die Preisuntergrenze, reichen für die optimale Preisgestaltung allein aber nicht aus", r: true },
      { t: "Nutzenorientierte Preisbildung basiert auf einem beim Kunden gemessenen Leistungs- bzw. Nutzenindex (z. B. Conjoint-Analyse)", r: true },
      { t: "Bei kostenorientierter Preisbildung werden Konkurrenz und Zahlungsbereitschaft der Kunden automatisch berücksichtigt" },
    ],
    musterantwort: "Kostenorientiert: Voll- oder Teilkosten plus Aufschlag; jede Kostenänderung führt zu proportionaler Preisänderung, andere Einflussgrößen werden ignoriert (Zirkelbezug); problematisch bei neuen Produkten (Gemeinkostenzuordnung). Nutzenorientiert: Zahlungsbereitschaft, idealerweise schon im Innovationsprozess (Target Costing); auch symbolische und emotionale Leistungen zählen.",
    erklaerung: "Genau das ist die Schwäche der Kosten-Plus-Methode: Wettbewerb und Kunden werden ignoriert.",
    seiten: "Folie 177–181",
  },
  {
    thema: "preis", quelle: "Skriptum",
    frage: "Welche Schritte gehören zur Preisfestsetzung als Managementprozess?",
    antworten: [
      { t: "Preisziele festlegen", r: true },
      { t: "Preisanalysen: eigene Kosten, Konkurrenzangebote und -preise, Nachfrager", r: true },
      { t: "Preisfestsetzung und Preisdurchsetzung (intern und extern)", r: true },
      { t: "Preiscontrolling (z. B. Rabattanalyse, Preiszufriedenheit)", r: true },
      { t: "Preise werden ausschließlich vom Vertrieb in der Kundenverhandlung festgelegt" },
    ],
    musterantwort: "1. Preisziele 2. Preisanalysen (Kosten, Wettbewerb, Nachfrager) 3. Preisfestsetzung 4. Preisdurchsetzung – intern (gemeinsames Ziel, Preiskultur, Preiskompetenz, Steuerung/Motivation) und extern (Preiskommunikation, Verhandlungen) 5. Preiscontrolling (qualitative und quantitative Preisziele).",
    erklaerung: "Herausforderungen: gesättigte Märkte/Preiskämpfe, Globalisierung, Produktvielfalt, hohe Preistransparenz, professionellere Einkaufsprozesse.",
    seiten: "Folie 171, 176, 182–183",
  },
  {
    thema: "preis", quelle: "Skriptum",
    frage: "Welche Aussagen zu den grundlegenden Preisstrategien (Preis-Leistungs-Positionen) treffen zu?",
    antworten: [
      { t: "Positionen im „Konsistenzband“ reichen von Ultraniedrig- über Niedrig-, Mittel-, Premium- bis Luxuspreisposition", r: true },
      { t: "Die Übervorteilungsposition bedeutet hoher Preis bei niedriger wahrgenommener Leistung", r: true },
      { t: "Die Vorteilsposition bedeutet hohe wahrgenommene Leistung bei niedrigem Preis", r: true },
      { t: "Die wahrgenommene Leistung umfasst nur funktionale, nicht emotionale oder symbolische Komponenten" },
    ],
    musterantwort: "Matrix: wahrgenommener relativer Preis × wahrgenommene relative Leistung (funktional, emotional, symbolisch). Konsistente Positionen liegen im Konsistenzband; Vorteils- und Übervorteilungsposition liegen außerhalb.",
    erklaerung: "Beispiele im Skriptum: Tata Nano (ultraniedrig), Hofer, VW Golf, Engel, A. Lange & Söhne (Luxus).",
    seiten: "Folie 173",
  },
  {
    thema: "dist", quelle: "Skriptum",
    frage: "Welche Aussagen zur Gestaltung des Absatzkanals und zur logistischen Dimension treffen zu?",
    antworten: [
      { t: "Tiefe eines Vertriebskanals = Anzahl der Vertriebsstufen zwischen Anbieter und Nachfrager", r: true },
      { t: "Breite eines Vertriebskanals = Anzahl der auf einer Vertriebsstufe eingesetzten Vertriebspartner", r: true },
      { t: "Zur logistischen Dimension gehören Auftragsabwicklung, Lagerhaltung, Lagerhäuser, Verpackung und Transport", r: true },
      { t: "Breite eines Vertriebskanals = Anzahl der Vertriebsstufen zwischen Anbieter und Nachfrager" },
    ],
    musterantwort: "Akquisitorische Dimension: Absatzkanalstruktur (direkt/indirekt; Tiefe, Breite, Anzahl der Kanäle). Logistische Dimension: Auftragsabwicklung, Lagerhaltung, Lagerhäuser/-plätze, Verpackung, Transport – Output ist der Lieferservice.",
    erklaerung: "Tiefe = Stufen, Breite = Partner pro Stufe.",
    seiten: "Folie 186–189",
  },
  {
    thema: "komm", quelle: "Skriptum",
    frage: "Welche Ziele der Kommunikationspolitik sind vorökonomisch?",
    antworten: [
      { t: "Aufbau von Awareness und Image", r: true },
      { t: "Aufbau und Stärkung von Kundenbeziehungen", r: true },
      { t: "Etablieren von Beziehungen zu weiteren Anspruchsgruppen", r: true },
      { t: "Steigerung von Absatz, Umsatz und Gewinn" },
    ],
    musterantwort: "Ökonomisch: Absatz, Umsatz, Gewinn (Erstkäufer gewinnen, Bedarf erhöhen, verlorene Kunden zurückgewinnen). Vorökonomisch: Awareness, Image, Kundenbeziehungen, Beziehungen zu Anspruchsgruppen.",
    erklaerung: "Absatz/Umsatz/Gewinn sind ökonomische Ziele.",
    seiten: "Folie 193",
  },
  {
    thema: "komm", quelle: "Skriptum",
    frage: "Welche Kommunikationsinstrumente sind richtig beschrieben?",
    antworten: [
      { t: "Werbung: von außen sofort als Unternehmenskommunikation erkennbar, vollständig vom Unternehmen kontrolliert", r: true },
      { t: "Verkaufsförderung: meist kurzfristige Maßnahmen mit Aktionscharakter, primär zur Erhöhung der Kaufbereitschaft", r: true },
      { t: "Sponsoring: Förderung von Personen/Organisationen/Veranstaltungen – wichtig ist die Imageaffinität", r: true },
      { t: "Public Relations: wird wie Werbung vollständig vom Unternehmen kontrolliert und dient vor allem kurzfristigen Absatzzielen" },
    ],
    musterantwort: "Instrumente: Werbung, Verkaufsförderung, PR, Direktmarketing, Messen, Event Marketing, digitales Marketing (+ Sponsoring). PR gestaltet die Beziehung zu Teilöffentlichkeiten, Ziel Vertrauen und Verständnis (leistungs-, unternehmens-, gesellschaftsbezogen) – im Gegensatz zur Werbung nicht vollständig kontrollierbar.",
    erklaerung: "Direktmarketing: je personalisierter, desto erfolgreicher; Event Marketing: hohe Dialogfähigkeit, Kundenbindung.",
    seiten: "Folie 195–203",
  },
  {
    thema: "komm", quelle: "Skriptum",
    frage: "Welche Formen der integrierten Kommunikation gibt es?",
    antworten: [
      { t: "Formale Integration: einheitliches äußeres Erscheinungsbild", r: true },
      { t: "Inhaltliche Integration: thematische Verbindung, einheitliche widerspruchsfreie Botschaften", r: true },
      { t: "Zeitliche Integration: zeitliche Abstimmung der Instrumente, Konsistenz & Kontinuität", r: true },
      { t: "Finanzielle Integration: alle Instrumente erhalten das gleiche Budget" },
    ],
    musterantwort: "Integrierte Kommunikation = formale, inhaltliche und zeitliche Integration (Synergien nutzen).",
    erklaerung: "Eine „finanzielle Integration“ gibt es im Skriptum nicht; das Budget wird bewusst auf Instrumente, Räume und Zeiten verteilt.",
    seiten: "Folie 205–206",
  },
  {
    thema: "komm", quelle: "Skriptum",
    frage: "Welche Aussagen zu Pretest und Posttest in der Kommunikation treffen zu?",
    antworten: [
      { t: "Der Pretest findet vor der Implementierung statt und adressiert vorökonomische Wirkungsziele", r: true },
      { t: "Einfache Pretest-Methoden sind die Portfolio-Methode und die Jury-Methode", r: true },
      { t: "Der Posttest adressiert vorökonomische und ökonomische Ziele, die Zurechenbarkeit ist aber schwierig", r: true },
      { t: "Der Posttest misst ausschließlich vorökonomische Ziele wie Aufmerksamkeit" },
    ],
    musterantwort: "Pretest: vor der Umsetzung, vorökonomisch (Aktivierung, kognitive, emotionale, einstellungsbezogene Wirkung), z. B. Portfolio- oder Jury-Methode. Posttest: nach der Umsetzung, vorökonomisch und ökonomisch (Umsatz, Gewinn, Neukunden) – schwierige Zurechenbarkeit wegen Verknüpfung mit anderen Instrumenten.",
    erklaerung: "Entscheidungsfelder der Kommunikationspolitik: Instrumente, Budget, Design & Test, Implementierung & Controlling.",
    seiten: "Folie 194, 207",
  },
  {
    thema: "komm", quelle: "Skriptum",
    frage: "Welche Aussagen zu AI im Kommunikationsmix treffen laut Skriptum zu?",
    antworten: [
      { t: "AI verändert Kommunikation von Massenkommunikation zu personalisierter Ansprache und von periodischen Kampagnen zu Echtzeit-Optimierung", r: true },
      { t: "Chancen sind u. a. Personalisierung, Geschwindigkeit, Effizienz und Messbarkeit", r: true },
      { t: "Risiken sind u. a. Datenschutz, Bias, Deepfakes und Kontrollverlust", r: true },
      { t: "Leitgedanke ist „Mensch oder AI“ – AI soll die Menschen im Marketing vollständig ersetzen" },
    ],
    musterantwort: "AI skaliert Kommunikation; Menschen sichern Strategie, Kreativität, Kontext und Verantwortung. Nicht „Mensch oder AI“, sondern klare Aufgabenverteilung, Regeln und Qualitätskontrolle.",
    erklaerung: "Exkurs am Ende des Skriptums.",
    seiten: "Folie 208–210",
  },
];

FRAGEN.forEach((f, i) => { f.nr = i + 1; });

FAECHER.push({
  id: "mom",
  name: "Marktorientiertes Management",
  kurz: "MOM",
  icon: "📈",
  untertitel: "MOM1IL · Klausurfragen + Skriptum",
  beschreibung: "Klausurformat: Mehrfachauswahl – mindestens eine Antwort ist richtig, es können auch alle richtig sein. Nur wenn genau alle richtigen angekreuzt sind, zählt die Frage. Fragen aus alten Klausuren sind markiert, die Lösungen stammen aus dem Skriptum.",
  quelleText: "Skriptum MOM1IL (Gaubinger, WS 2026/27)",
  nrLabel: "Nr.",
  mehrfach: true,
  store: "lernquiz-mom-v1",
  themen: THEMEN,
  fragen: FRAGEN,
});
}
