// Fragenkatalog CHE1VO/ACA1VO_bb (WS 26/27) – alle 58 Fragen im Originalwortlaut.
// Alle Antworten stammen aus dem Skriptum ACA1VO/CHE1VO (Forsich):
//   richtig        – kurze richtige Antwortmöglichkeit (ähnlich lang wie die falschen)
//   musterantwort  – ausführliche Antwort, wird nach dem Antworten angezeigt
//   erklaerung     – Zusatzinfo; seiten – Folien-/Seitennummern im Skriptum
// Beim Spielen werden die Antwortmöglichkeiten zufällig gemischt.

window.FAECHER = window.FAECHER || [];
{
const THEMEN = {
  einf: "Einführung & Stoffe",
  atom: "Atombau",
  pse: "Periodensystem",
  bdg: "Chemische Bindung",
  reak: "Reaktionen, Energie & Kinetik",
  ggw: "Chemisches Gleichgewicht",
  sb: "Säuren & Basen",
  redox: "Redox & Elektrochemie",
};

const FRAGEN = [
  {
    nr: 1, thema: "einf",
    frage: "Was versteht man unter physikalischen und chemischen Eigenschaften der Materie?",
    richtig: "Physikalische Eigenschaften (Farbe, Dichte, Siedepunkt) beschreiben einen Stoff, ohne seine Identität zu ändern; chemische Eigenschaften beschreiben, wie er unter Bildung neuer Stoffe reagiert.",
    musterantwort: "Physikalische Eigenschaften (z. B. Farbe, Dichte, Schmelz-/Siedetemperatur) lassen sich beschreiben, ohne dass sich die Identität des Stoffes ändert (z. B. Schmelzen von Eis). Chemische Eigenschaften (Zusammensetzung, Reaktivität) beschreiben, wie ein Stoff mit anderen reagiert und dabei neue Stoffe bildet (z. B. Rosten von Eisen).",
    falsch: [
      "Physikalische Eigenschaften beschreiben, wie ein Stoff mit anderen reagiert (z. B. Brennbarkeit); chemische Eigenschaften sind messbare Größen wie Dichte, Farbe und Siedepunkt, bei denen der Stoff erhalten bleibt.",
      "Physikalische Eigenschaften betreffen nur Elemente, chemische Eigenschaften nur Verbindungen; ein Element kann daher keine chemischen Eigenschaften besitzen.",
      "Physikalische Eigenschaften hängen von der Menge des Stoffes ab (Masse, Volumen), chemische Eigenschaften nur von der Temperatur; beim Schmelzen von Eis ändert sich daher die chemische Zusammensetzung.",
    ],
    erklaerung: "Physikalische Veränderung: Identität des Stoffes bleibt erhalten (Eis → Wasser ändert nur den Aggregatzustand). Chemische Veränderung: Es entstehen neue Stoffe mit neuen Eigenschaften (Fe + O₂ → Eisenoxid/Rost).",
    seiten: "S. 10–12",
  },
  {
    nr: 2, thema: "einf",
    frage: "Was ist der Unterschied zwischen einem Reinstoff und einem Stoffgemisch? Erläutern Sie die Merkmale beider Stoffklassen und nennen Sie jeweils ein Beispiel.",
    richtig: "Ein Reinstoff ist bis ins Mikroskopische einheitlich zusammengesetzt (z. B. Wasser); ein Stoffgemisch variiert und lässt sich physikalisch trennen (z. B. Zuckerwasser).",
    musterantwort: "Ein Reinstoff hat bis auf die mikroskopische Ebene eine einheitliche Zusammensetzung und einheitliche Eigenschaften (z. B. Wasser, Zucker). Ein Stoffgemisch kann in Zusammensetzung und Eigenschaften variieren; seine Bestandteile lassen sich ohne Änderung ihrer chemischen Identität trennen (z. B. Zuckerwasser).",
    falsch: [
      "Ein Reinstoff besteht immer nur aus einer einzigen Atomsorte (z. B. Gold); ein Stoffgemisch ist jede Verbindung aus mehreren Elementen (z. B. Wasser).",
      "Ein Reinstoff ist immer farblos und durchsichtig (z. B. Wasser); ein Stoffgemisch erkennt man immer daran, dass man die Bestandteile mit bloßem Auge sieht (z. B. Zuckerwasser).",
      "Ein Stoffgemisch hat eine feste, unveränderliche Zusammensetzung (z. B. Kochsalz); die Bestandteile eines Reinstoffs lassen sich durch Sieden oder Filtrieren trennen (z. B. Wasser).",
    ],
    erklaerung: "Zuckerwasser: Wasser lässt sich durch Sieden und Kondensieren zurückgewinnen, der Zucker bleibt zurück – beide Bestandteile behalten ihre chemische Identität.",
    seiten: "S. 13–15, 18",
  },
  {
    nr: 3, thema: "einf",
    frage: "Worin unterscheiden sich homogene und heterogene Gemische? Beschreiben Sie die Unterschiede anhand eines konkreten Beispiels.",
    richtig: "Ein homogenes Gemisch ist auf mikroskopischer Ebene einheitlich, die Bestandteile sind nicht unterscheidbar (Zucker in Wasser); ein heterogenes ist uneinheitlich (Sand in Wasser).",
    musterantwort: "Ein homogenes Gemisch hat auf mikroskopischer Ebene eine einheitliche Zusammensetzung, die Bestandteile sind nicht unterscheidbar (z. B. in Wasser gelöster Zucker). Ein heterogenes Gemisch ist uneinheitlich zusammengesetzt, die Bestandteile sind sichtbar (z. B. Suspension aus Sand und Wasser).",
    falsch: [
      "Ein homogenes Gemisch besteht aus zwei gleichen Stoffen (z. B. Wasser und Eis), ein heterogenes Gemisch aus zwei verschiedenen Stoffen (z. B. Zucker in Wasser).",
      "Ein heterogenes Gemisch hat überall dieselbe Zusammensetzung (z. B. Zuckerwasser), ein homogenes Gemisch zeigt sichtbar unterschiedliche Bereiche (z. B. Sand in Wasser).",
      "Homogene Gemische lassen sich nicht mehr trennen, weil dabei eine chemische Reaktion abgelaufen ist (z. B. Zuckerwasser); nur heterogene Gemische sind trennbar (z. B. Sand in Wasser).",
    ],
    erklaerung: "Zuckerwasser sieht aus wie reines Wasser, unterscheidet sich aber auf molekularer Ebene (homogen). Bei Sand in Wasser ist die Zusammensetzung nicht überall gleich (heterogen).",
    seiten: "S. 14–15",
  },
  {
    nr: 4, thema: "einf",
    frage: "Was ist ein chemisches Element und wie unterscheidet es sich von einer chemischen Verbindung? Geben Sie jeweils ein Beispiel an.",
    richtig: "Ein Element besteht aus einer Atomsorte und ist chemisch nicht zerlegbar (z. B. Gold); eine Verbindung aus mehreren Elementen in festem Verhältnis ist zerlegbar (z. B. Wasser).",
    musterantwort: "Ein Element ist ein Reinstoff aus nur einer Atomsorte, der chemisch nicht in einfachere Stoffe zerlegt werden kann (z. B. Sauerstoff, Gold). Eine Verbindung besteht aus zwei oder mehr Elementen in festem Verhältnis und lässt sich chemisch in ihre Elemente zerlegen (z. B. Wasser → H₂ + O₂ durch Elektrolyse).",
    falsch: [
      "Ein Element besteht immer aus Einzelatomen (z. B. Wasserstoff H), eine Verbindung immer aus Molekülen; daher ist H₂ bereits eine chemische Verbindung.",
      "Ein Element lässt sich durch Erhitzen in einfachere Stoffe zerlegen (z. B. Schwefel), eine Verbindung dagegen gar nicht mehr (z. B. Wasser).",
      "Ein Element ist ein Gemisch verschiedener Atome mit gleicher Masse (z. B. Luft), eine Verbindung ein Gemisch mit variabler Zusammensetzung (z. B. Salzwasser).",
    ],
    erklaerung: "Element: nicht chemisch zerlegbar, eine einzige Atomsorte (118 bekannte Elemente). Verbindung: zwei oder mehr verschiedene Elemente in festem Verhältnis, chemisch zerlegbar.",
    seiten: "S. 16–17, 19, 27",
  },
  {
    nr: 5, thema: "einf",
    frage: "Warum sind O₂ und O₃ keine chemischen Verbindungen, obwohl sie aus mehreren Atomen bestehen?",
    richtig: "Weil sie nur aus Sauerstoffatomen bestehen – es sind Formen des Elements Sauerstoff, keine Verbindung verschiedener Elemente.",
    musterantwort: "Weil sie ausschließlich aus Sauerstoffatomen bestehen – es sind unterschiedliche Formen des Elements Sauerstoff. Eine Verbindung muss zwei oder mehr verschiedene Elemente enthalten.",
    falsch: [
      "Weil die Atome in O₂ und O₃ nicht durch chemische Bindungen, sondern nur durch Van-der-Waals-Kräfte zusammengehalten werden.",
      "Weil O₂ und O₃ Gase sind – chemische Verbindungen müssen bei Raumtemperatur fest oder flüssig sein.",
      "Weil O₂ und O₃ Ionen sind und Ionen grundsätzlich nicht zu den chemischen Verbindungen gezählt werden.",
    ],
    erklaerung: "O₂ (Sauerstoffmolekül) und O₃ (Ozon) sind molekulare Elemente. Ähnlich: H₂, N₂, Halogene (F₂, Cl₂, Br₂, I₂), P₄, S₈.",
    seiten: "S. 20–21",
  },
  {
    nr: 6, thema: "atom",
    frage: "Aus welchen Teilchen besteht ein Atom? Welche Teilchen bilden die Hauptmasse?",
    richtig: "Aus Protonen und Neutronen im Kern sowie Elektronen in der Hülle. Die Hauptmasse bilden die Nukleonen (Protonen und Neutronen) im Atomkern.",
    musterantwort: "Aus Protonen (positiv) und Neutronen (neutral) im Atomkern sowie Elektronen (negativ) in der Atomhülle. Die Hauptmasse bilden die Nukleonen (Protonen und Neutronen, je ca. 1,67·10⁻²⁷ kg) im Kern; ein Elektron hat nur ca. 9,11·10⁻³¹ kg.",
    falsch: [
      "Aus Protonen und Elektronen im Kern sowie Neutronen in der Hülle. Die Hauptmasse bilden die Elektronen, weil sie fast das gesamte Volumen des Atoms einnehmen.",
      "Aus Protonen (positiv), Neutronen (negativ) und Elektronen (neutral). Protonen, Neutronen und Elektronen tragen etwa gleich viel zur Masse bei.",
      "Aus Protonen und Neutronen in der Hülle und Elektronen im Kern. Die Hauptmasse bilden die Neutronen allein, Protonen sind nahezu masselos.",
    ],
    erklaerung: "Rutherford: winziger Kern (ca. 1 fm) mit fast der gesamten Masse und der ganzen positiven Ladung; die Elektronen nehmen fast das ganze Volumen ein (Atom ca. 100 000-mal größer als der Kern).",
    seiten: "S. 46, 48–49",
  },
  {
    nr: 7, thema: "atom",
    frage: "Was gibt die Ordnungszahl bzw. die Massenzahl eines Elementes an?",
    richtig: "Die Ordnungszahl gibt die Anzahl der Protonen an, die Massenzahl die Anzahl der Protonen plus Neutronen.",
    musterantwort: "Die Ordnungszahl (Kernladungszahl) Z gibt die Anzahl der Protonen an (im neutralen Atom = Anzahl der Elektronen). Die Massenzahl (Nukleonenzahl) A gibt die Gesamtzahl der Nukleonen, also Protonen + Neutronen, an.",
    falsch: [
      "Die Ordnungszahl gibt die Anzahl der Neutronen an, die Massenzahl die Anzahl der Protonen plus Elektronen.",
      "Die Ordnungszahl gibt die Anzahl der Elektronenschalen an, die Massenzahl die Masse des Atoms in Gramm.",
      "Die Ordnungszahl gibt die Anzahl der Nukleonen an, die Massenzahl die Anzahl der Valenzelektronen.",
    ],
    erklaerung: "Schreibweise: Massenzahl A links oben, Ordnungszahl Z links unten am Elementsymbol. Neutronenzahl = A − Z (z. B. ⁵⁶Fe: 56 − 26 = 30 Neutronen).",
    seiten: "S. 50–52, 66",
  },
  {
    nr: 8, thema: "atom",
    frage: "Definieren Sie den Molbegriff.",
    richtig: "1 Mol ist die Stoffmenge, die so viele Teilchen enthält, wie Atome in 12 g ¹²C enthalten sind – das sind 6,022·10²³ Teilchen.",
    musterantwort: "1 Mol ist die Stoffmenge, die aus genauso vielen Teilchen besteht, wie Atome in 12 g des Kohlenstoffnuklids ¹²C enthalten sind – das sind 6,022·10²³ Teilchen (Avogadro-Zahl Nₐ). Die molare Masse M ist die Masse von 1 mol in Gramm; n = m/M.",
    falsch: [
      "1 Mol ist die Stoffmenge, die aus genauso vielen Teilchen besteht, wie Atome in 1 g Wasserstoff enthalten sind – das sind 6,022·10²⁶ Teilchen.",
      "1 Mol ist die Masse eines einzelnen Atoms in Gramm; die Avogadro-Zahl gibt an, wie viele Protonen ein Atom enthält.",
      "1 Mol ist das Volumen von 1 Liter eines beliebigen Stoffes; es enthält je nach Stoff unterschiedlich viele Teilchen.",
    ],
    erklaerung: "Das Mol ist eine SI-Basiseinheit („das Dutzend des Chemikers“). 1 mol = Formelgewicht in Gramm = Nₐ Formeleinheiten = 22,41 L eines idealen Gases.",
    seiten: "S. 61–64",
  },
  {
    nr: 9, thema: "atom",
    frage: "Was versteht man unter Orbitalen? Skizzieren bzw. beschreiben Sie s-, p- und d-Orbitale.",
    richtig: "Ein Orbital ist die Wellenfunktion ψ eines Elektrons (ψ² ~ Aufenthaltswahrscheinlichkeit). s-Orbitale sind kugelförmig, p-Orbitale hantelförmig, d-Orbitale meist rosettenförmig.",
    musterantwort: "Ein Orbital ist die Wellenfunktion ψ eines Elektrons im Atom; ψ² ist proportional zur Aufenthaltswahrscheinlichkeit (Darstellung: Grenzfläche mit 90 % Wahrscheinlichkeit). s-Orbitale sind kugelförmig, die drei p-Orbitale hantelförmig mit Knotenebene durch den Kern, die fünf d-Orbitale meist rosettenförmig (vier Lappen), Aufenthaltswahrscheinlichkeit am Kern null.",
    falsch: [
      "Ein Orbital ist eine feste Kreisbahn, auf der sich das Elektron mit genau bekanntem Ort und Impuls bewegt. s-Orbitale sind hantelförmig, p-Orbitale kugelförmig, d-Orbitale ringförmig.",
      "Ein Orbital ist der Bereich im Atomkern, in dem sich Protonen aufhalten. Es gibt ein s-, drei d- und fünf p-Orbitale pro Schale.",
      "Ein Orbital ist eine Elektronenschale (K, L, M …), die beliebig viele Elektronen aufnehmen kann. s-, p- und d-Orbitale unterscheiden sich nur in ihrer Größe, nicht in ihrer Form.",
    ],
    erklaerung: "Heisenberg: Ort und Impuls sind nicht gleichzeitig exakt bestimmbar – daher nur Aufenthaltswahrscheinlichkeiten (Schrödingergleichung). Anzahl: 1 s-, 3 p-, 5 d-, 7 f-Orbitale je Unterschale.",
    seiten: "S. 78–79, 84–88",
  },
  {
    nr: 10, thema: "atom",
    frage: "Welche Quantenzahlen kennen Sie (mit Beschreibung)?",
    richtig: "Hauptquantenzahl n: Energie/Schale. Nebenquantenzahl l (0 bis n−1): Form (s, p, d, f). Magnetquantenzahl mₗ (−l bis +l): Orientierung. Spinquantenzahl mₛ: ±½.",
    musterantwort: "Hauptquantenzahl n (1, 2, 3 …): Energie und Größe des Orbitals, Schale. Nebenquantenzahl l (0 bis n−1): Form des Orbitals (s, p, d, f). Magnetquantenzahl mₗ (−l bis +l): räumliche Orientierung, 2l+1 Orbitale. Spinquantenzahl mₛ (+½ oder −½): Eigendrehimpuls des Elektrons.",
    falsch: [
      "Hauptquantenzahl n: Form des Orbitals. Nebenquantenzahl l (1 bis n): Energie der Schale. Magnetquantenzahl mₗ: Spin des Elektrons (±1). Spinquantenzahl mₛ: Anzahl der Orbitale pro Schale.",
      "Es gibt nur zwei Quantenzahlen: die Hauptquantenzahl n für die Schale und die Spinquantenzahl mₛ (0 oder 1) für die Drehrichtung des Elektrons.",
      "Hauptquantenzahl n (0, 1, 2 …): Anzahl der Elektronen. Nebenquantenzahl l (0 bis n): Anzahl der Protonen. Magnetquantenzahl mₗ (0 bis l): Masse. Spinquantenzahl mₛ (+1 oder −1): Ladung des Elektrons.",
    ],
    erklaerung: "Orbitale pro Schale: n², Elektronen pro Schale: 2n² (K: 2, L: 8, M: 18). l = 0 → s, 1 → p, 2 → d, 3 → f.",
    seiten: "S. 80–83",
  },
  {
    nr: 11, thema: "pse",
    frage: "Beschreiben Sie den Aufbau des Periodensystems.",
    richtig: "Die Elemente sind nach steigender Ordnungszahl angeordnet; 7 Perioden (Zeilen, Zahl der Schalen) und 18 Gruppen (Spalten, gleiche Valenzelektronen → ähnliche Eigenschaften).",
    musterantwort: "Die Elemente sind nach steigender Ordnungszahl angeordnet. Die 7 waagrechten Perioden (2, 8, 8, 18, 18, 32, 32 Elemente) entsprechen der Zahl besetzter Schalen; die 18 senkrechten Gruppen enthalten Elemente mit gleicher Valenzelektronenkonfiguration und ähnlichen Eigenschaften. Man unterscheidet Hauptgruppen (s-/p-Block), Nebengruppen (d-Block) sowie Lanthanoide/Actinoide (f-Block).",
    falsch: [
      "Die Elemente sind nach steigender Atommasse angeordnet. Es gibt 18 Perioden (Spalten) und 7 Gruppen (Zeilen); alle Perioden enthalten gleich viele Elemente.",
      "Die Elemente sind alphabetisch nach ihren lateinischen Namen angeordnet; Metalle stehen oben, Nichtmetalle unten, die Edelgase ganz links.",
      "Die Elemente sind nach der Anzahl ihrer Neutronen angeordnet. Elemente einer Periode (Zeile) haben ähnliche chemische Eigenschaften, Elemente einer Gruppe gleich viele Schalen.",
    ],
    erklaerung: "Periodennummer = Anzahl der besetzten Schalen; Einerstelle der Gruppennummer = Anzahl der Valenzelektronen. Blöcke nach der Unterschale, die zuletzt Elektronen aufnimmt: s-, p-, d-, f-Block.",
    seiten: "S. 93–96, 118–128",
  },
  {
    nr: 12, thema: "pse",
    frage: "Tragen Sie in einem Energieniveaudiagramm die Orbitalenergien der ersten 5. Perioden ein. Geben Sie des weiters in diesem Diagramm die Elektronenkonfiguration von P an.",
    richtig: "Reihenfolge: 1s < 2s < 2p < 3s < 3p < 4s < 3d < 4p < 5s < 4d < 5p. Phosphor: [Ne] 3s² 3p³, die drei 3p-Elektronen einzeln mit parallelem Spin.",
    musterantwort: "Reihenfolge steigender Energie: 1s < 2s < 2p < 3s < 3p < 4s < 3d < 4p < 5s < 4d < 5p. Phosphor (Z = 15): 1s² 2s² 2p⁶ 3s² 3p³ = [Ne] 3s² 3p³ – die drei 3p-Elektronen sitzen nach der Hundschen Regel einzeln mit parallelem Spin in den drei 3p-Orbitalen.",
    falsch: [
      "Reihenfolge: 1s < 2s < 2p < 3s < 3p < 3d < 4s < 4p < 4d < 5s < 5p. Phosphor: 1s² 2s² 2p⁶ 3s² 3p³, wobei zwei 3p-Elektronen gepaart in einem Orbital sitzen.",
      "Reihenfolge: 1s < 2s < 2p < 3s < 3p < 4s < 3d < 4p < 5s < 4d < 5p. Phosphor: 1s² 2s² 2p⁶ 3s¹ 3p⁴ = [Ne] 3s¹ 3p⁴.",
      "Reihenfolge: 1s < 2p < 2s < 3p < 3s < 3d < 4p < 4s < 5p < 4d < 5s. Phosphor: 1s² 2s² 2p⁶ 3s² 3p² 3d¹.",
    ],
    erklaerung: "In Mehrelektronen-Atomen gilt innerhalb einer Schale s < p < d; ab Z = 21 liegt 4s unter 3d. Hundsche Regel: energiegleiche Orbitale werden zuerst einfach mit parallelem Spin besetzt.",
    seiten: "S. 98–103, 109, 112, 117",
  },
  {
    nr: 13, thema: "pse",
    frage: "Nach welchen Regeln werden die einzelnen Orbitale mit Elektronen besetzt?",
    richtig: "1) Aufbauprinzip: niedrigste Energie zuerst. 2) Pauli-Prinzip: max. 2 Elektronen mit entgegengesetztem Spin pro Orbital. 3) Hundsche Regel: gleichwertige Orbitale erst einfach besetzen.",
    musterantwort: "1) Aufbauprinzip: zuerst das niedrigste mögliche Energieniveau. 2) Pauli-Prinzip: Keine zwei Elektronen dürfen in allen vier Quantenzahlen übereinstimmen – max. 2 Elektronen pro Orbital mit entgegengesetztem Spin. 3) Hundsche Regel: Energiegleiche Orbitale werden zuerst einzeln mit parallelem Spin besetzt.",
    falsch: [
      "1) Zuerst werden die Orbitale mit der höchsten Energie besetzt. 2) Pauli-Prinzip: Jedes Orbital kann bis zu 8 Elektronen aufnehmen. 3) Hundsche Regel: Elektronen paaren sich immer sofort in einem Orbital.",
      "1) Die Orbitale werden in der Reihenfolge s → p → d → f einer Schale komplett gefüllt, bevor die nächste Schale beginnt. 2) Jedes Orbital enthält immer genau ein Elektron. 3) Alle Elektronen haben denselben Spin.",
      "1) Elektronen besetzen Orbitale zufällig. 2) Pauli-Prinzip: Zwei Elektronen in einem Orbital müssen denselben Spin haben. 3) Hundsche Regel: Energiegleiche Orbitale werden zuerst doppelt besetzt.",
    ],
    erklaerung: "Beispiel Kohlenstoff: 1s² 2s² 2p² – die beiden 2p-Elektronen sitzen in verschiedenen p-Orbitalen mit parallelem Spin (maximale Multiplizität).",
    seiten: "S. 103–104, 109",
  },
  {
    nr: 14, thema: "pse",
    frage: "Was versteht man unter „Periode“ bzw. „Gruppe“ im PSE und was bedeuten sie?",
    richtig: "Eine Periode ist eine waagrechte Zeile (Zahl der Schalen), eine Gruppe eine senkrechte Spalte mit gleich vielen Valenzelektronen und ähnlichen Eigenschaften.",
    musterantwort: "Eine Periode ist eine waagrechte Zeile; ihre Nummer gibt die Anzahl der mit Elektronen besetzten Schalen an. Eine Gruppe ist eine senkrechte Spalte; ihre Elemente haben die gleiche Valenzelektronenkonfiguration (gleich viele Valenzelektronen) und daher ähnliche chemische Eigenschaften.",
    falsch: [
      "Eine Periode ist eine senkrechte Spalte mit chemisch ähnlichen Elementen; eine Gruppe ist eine waagrechte Zeile, deren Nummer die Anzahl der Schalen angibt.",
      "Eine Periode fasst alle Elemente mit gleicher Massenzahl zusammen, eine Gruppe alle Elemente mit gleicher Neutronenzahl.",
      "Periode und Gruppe bedeuten dasselbe; beide bezeichnen die Blöcke s, p, d und f im Periodensystem.",
    ],
    erklaerung: "Beispiele: Gruppe 18 (Edelgase) – farblose, reaktionsträge Gase; Gruppe 17 (Halogene) – reaktive Elemente. Hauptgruppennummer = Anzahl der Valenzelektronen.",
    seiten: "S. 94, 96, 120, 124, 129",
  },
  {
    nr: 15, thema: "pse",
    frage: "Wodurch zeichnet sich die Edelgaskonfiguration aus?",
    richtig: "Durch eine voll besetzte Valenzschale: Oktett ns² np⁶ (He: 1s²). Sie ist energetisch besonders stabil, Edelgase sind daher reaktionsträge.",
    musterantwort: "Durch eine vollständig gefüllte Valenzschale: 8 Elektronen (ns² np⁶, Elektronenoktett) bzw. beim Helium 2 Elektronen (1s², Duplett). Diese Konfiguration ist energetisch besonders günstig – Edelgase sind reaktionsträge, kommen atomar vor und haben hohe Ionisierungsenergien. Andere Atome streben sie bei Reaktionen an.",
    falsch: [
      "Durch eine halb gefüllte Valenzschale mit 4 Elektronen; diese Konfiguration ist besonders reaktiv, deshalb reagieren Edelgase heftig mit Metallen.",
      "Durch eine leere Valenzschale ohne Elektronen; Edelgase haben daher keine Elektronenhülle und sehr niedrige Ionisierungsenergien.",
      "Durch genau ein Valenzelektron in der äußersten Schale, das sehr leicht abgegeben wird – daher bilden Edelgase leicht einfach positive Ionen.",
    ],
    erklaerung: "Triebkraft chemischer Reaktionen ist (meist) das Erreichen des Oktetts. Metalle geben dazu Elektronen ab, Nichtmetalle nehmen welche auf oder teilen Elektronenpaare.",
    seiten: "S. 105, 112, 114, 153, 171",
  },
  {
    nr: 16, thema: "pse",
    frage: "Wo befinden sich im Periodensystem die Metalle und die Nichtmetalle (mit Begründung)?",
    richtig: "Metalle stehen links unten, Nichtmetalle rechts oben. Grund: Links unten sind Ionisierungsenergie und EN klein, Elektronen werden leicht abgegeben; rechts oben groß.",
    musterantwort: "Metalle stehen links und unten (inkl. aller Nebengruppen, Lanthanoide, Actinoide), Nichtmetalle rechts oben; dazwischen liegen die Halbmetalle (B, Si, Ge, As, Sb, Te). Grund: Links/unten sind Ionisierungsenergie und Elektronegativität klein – die wenigen Valenzelektronen werden leicht abgegeben (Kationenbildung). Rechts oben sind sie groß – Elektronen werden aufgenommen.",
    falsch: [
      "Metalle stehen rechts oben, Nichtmetalle links unten. Grund: Rechts oben haben die Atome die größten Radien und geben ihre Elektronen daher am leichtesten ab.",
      "Metalle und Nichtmetalle wechseln sich in jeder Periode regelmäßig ab. Grund: Elemente mit gerader Ordnungszahl sind Metalle, mit ungerader Nichtmetalle.",
      "Metalle stehen nur in den Hauptgruppen 1 und 2, alle anderen Elemente sind Nichtmetalle. Grund: Nur Alkali- und Erdalkalimetalle besitzen Valenzelektronen.",
    ],
    erklaerung: "Elemente mit geringer Ionisierungsenergie (s-, d-, f-Block, linke p-Blockelemente) haben metallischen Charakter. Etwa vier Fünftel aller Elemente sind Metalle; der metallische Charakter wächst in den Hauptgruppen von oben nach unten.",
    seiten: "S. 134–135, 154, 161–162, 296",
  },
  {
    nr: 17, thema: "pse",
    frage: "Beschreiben Sie den Begriff „Ion“ und nennen Sie Beispiele.",
    richtig: "Ein Ion ist ein elektrisch geladenes Atom oder Molekül: Elektronenabgabe ergibt ein Kation (z. B. Na⁺, Mg²⁺), Elektronenaufnahme ein Anion (z. B. Cl⁻, O²⁻).",
    musterantwort: "Ein Ion ist ein elektrisch geladenes Atom (oder Molekül). Gibt ein Atom Elektronen ab, entsteht ein positiv geladenes Kation (z. B. Na⁺, Mg²⁺, Al³⁺); nimmt es Elektronen auf, entsteht ein negativ geladenes Anion (z. B. F⁻, Cl⁻, O²⁻). Auch mehratomige Ionen wie SO₄²⁻ oder NO₃⁻ existieren.",
    falsch: [
      "Ein Ion ist ein Atom mit einer abweichenden Neutronenzahl (z. B. ²H, ¹⁴C); durch zusätzliche Neutronen wird es elektrisch geladen.",
      "Ein Ion ist ein neutrales Molekül aus zwei gleichen Atomen (z. B. H₂, Cl₂); es entsteht, wenn sich zwei Atome ein Elektronenpaar teilen.",
      "Ein Ion entsteht, wenn ein Atom Protonen abgibt oder aufnimmt: Protonenabgabe ergibt ein Anion (z. B. Na⁻), Protonenaufnahme ein Kation (z. B. Cl⁺).",
    ],
    erklaerung: "Metalle (links im PSE) bilden eher Kationen, Nichtmetalle (rechts) eher Anionen – Triebkraft ist die Edelgaskonfiguration. Beispiele: I → I⁻, Al → Al³⁺.",
    seiten: "S. 30, 132–136",
  },
  {
    nr: 18, thema: "pse",
    frage: "Was versteht man unter Atomradius und wie ändert er sich innerhalb des PSE (mit Begründung)?",
    richtig: "Der Atomradius ist der halbe Kernabstand zweier gebundener Atome. Er nimmt in der Periode ab (höhere effektive Kernladung) und in der Gruppe zu (zusätzliche Schalen).",
    musterantwort: "Der Atomradius ist der halbe Abstand zweier Atomkerne in einer chemischen Verbindung (z. B. Cu: 270 pm / 2 = 135 pm). Er nimmt innerhalb einer Periode ab (steigende effektive Kernladung, Elektronen kommen in dieselbe Schale) und innerhalb einer Gruppe zu (zunehmend äußere Schalen werden besetzt).",
    falsch: [
      "Der Atomradius ist der Abstand vom Kern bis zum äußersten Proton. Er nimmt innerhalb einer Periode zu (mehr Elektronen brauchen mehr Platz) und innerhalb einer Gruppe ab.",
      "Der Atomradius ist der Radius des Atomkerns. Er ist für alle Elemente einer Periode gleich und nimmt nur innerhalb einer Gruppe ab, weil die Kernladung steigt.",
      "Der Atomradius ist der doppelte Abstand zweier Atomkerne. Er nimmt innerhalb einer Periode und innerhalb einer Gruppe gleichermaßen zu, weil die Masse steigt.",
    ],
    erklaerung: "Innerhalb der Periode verteilen sich die zusätzlichen Elektronen in derselben Schale und schirmen sich kaum ab, während die Protonenzahl steigt → stärkere Anziehung, kleinerer Radius.",
    seiten: "S. 138–139",
  },
  {
    nr: 19, thema: "pse",
    frage: "Was sind Kationen bzw. Anionen und wie unterscheiden sie sich untereinander (mit Begründung)?",
    richtig: "Kationen sind positiv und kleiner als das Atom (weniger Elektronen, stärker angezogen); Anionen sind negativ und größer als das Atom (mehr Elektronen, stärkere Abstoßung).",
    musterantwort: "Kationen sind positiv geladen (Elektronenabgabe) und deutlich kleiner als das Atom: weniger Elektronen als Kernladung → Hülle stärker zusammengezogen, oft eine Schale weniger (Li 157 pm → Li⁺ 58 pm). Anionen sind negativ geladen (Elektronenaufnahme) und größer als das Atom: mehr Elektronen als Kernladung, stärkere gegenseitige Abstoßung (O 66 pm → O²⁻ 140 pm).",
    falsch: [
      "Kationen sind negativ geladen und größer als das Atom, weil zusätzliche Elektronen mehr Platz brauchen; Anionen sind positiv geladen und kleiner, weil Elektronen fehlen.",
      "Kationen und Anionen sind immer gleich groß wie das neutrale Atom, da sich nur die Ladung, nicht aber die Elektronenhülle ändert.",
      "Kationen sind positiv geladen und größer als das Atom, weil die positive Ladung die Hülle aufbläht; Anionen sind negativ geladen und kleiner, weil der Kern die zusätzlichen Elektronen stärker anzieht.",
    ],
    erklaerung: "Die Radien von Kationen und Anionen nehmen – wie die Atomradien – innerhalb einer Periode ab und innerhalb einer Gruppe zu.",
    seiten: "S. 132, 144–145, 147, 173",
  },
  {
    nr: 20, thema: "pse",
    frage: "Erklären Sie den Begriff „isoelektronisch“ und nennen Sie Beispiele.",
    richtig: "Isoelektronische Teilchen haben die gleiche Elektronenkonfiguration, z. B. Na⁺, F⁻ und Mg²⁺ (wie Ne); je höher die Kernladung, desto kleiner.",
    musterantwort: "Isoelektronische Teilchen haben die gleiche Anzahl an Elektronen bzw. die identische Elektronenkonfiguration. Beispiel: Na⁺, F⁻ und Mg²⁺ haben alle [He] 2s² 2p⁶ (wie Neon). Je höher die Kernladung, desto kleiner der Radius: Mg²⁺ (72 pm) < Na⁺ (102 pm) < F⁻ (133 pm).",
    falsch: [
      "Isoelektronische Teilchen haben die gleiche Anzahl an Protonen, aber unterschiedlich viele Neutronen. Beispiel: ¹H, ²H und ³H.",
      "Isoelektronische Teilchen haben die gleiche Ladung. Beispiel: Na⁺, K⁺ und Li⁺ – sie sind alle gleich groß.",
      "Isoelektronische Teilchen stehen in derselben Gruppe des PSE. Beispiel: F, Cl, Br – ihr Radius nimmt mit steigender Kernladung zu.",
    ],
    erklaerung: "Bei gleicher Elektronenzahl zeigt sich direkt der Einfluss der Kernladungszahl: mehr Protonen ziehen dieselben Elektronen stärker an.",
    seiten: "S. 146",
  },
  {
    nr: 21, thema: "pse",
    frage: "Was ist die Ionisierungsenergie? Wie ändert sich die Ionisierungsenergie innerhalb des PSE (mit Begründung)?",
    richtig: "Die Ionisierungsenergie ist die Mindestenergie zum Entfernen eines Elektrons aus einem freien Atom. Sie steigt in der Periode (kleinerer Radius) und sinkt in der Gruppe (größerer Radius).",
    musterantwort: "Die (1.) Ionisierungsenergie ist die Energie, die mindestens aufgewendet werden muss, um ein Elektron aus einem freien, gasförmigen Atom im Grundzustand zu entfernen (→ Kation). Sie nimmt innerhalb einer Periode zu (kleinerer Radius, höhere Kernladung) und innerhalb einer Gruppe ab (größerer Radius, Elektronen weiter vom Kern entfernt).",
    falsch: [
      "Die Ionisierungsenergie ist die Energie, die frei wird, wenn ein Atom ein zusätzliches Elektron aufnimmt. Sie nimmt innerhalb einer Periode ab und innerhalb einer Gruppe zu.",
      "Die Ionisierungsenergie ist die Energie, die nötig ist, um ein Proton aus dem Kern zu entfernen. Sie ist für alle Elemente gleich groß.",
      "Die Ionisierungsenergie ist die Energie zur Abspaltung eines Elektrons. Sie nimmt innerhalb einer Periode ab (mehr Elektronen stoßen sich ab) und innerhalb einer Gruppe zu (mehr Schalen halten die Elektronen fester).",
    ],
    erklaerung: "Die kleinsten Ionisierungsenergien findet man links und unten im PSE (z. B. Cs), die größten bei den Edelgasen. Voll- oder halbbesetzte Unterschalen (Be, N) haben unerwartet hohe Werte.",
    seiten: "S. 148–153",
  },
  {
    nr: 22, thema: "pse",
    frage: "Definieren Sie die Elektronegativität. Wie ändert sich die Elektronegativität innerhalb des Periodensystems (mit Begründung)?",
    richtig: "Die Elektronegativität ist die Fähigkeit eines Atoms, Bindungselektronen anzuziehen (Fluor = 4). Sie steigt in der Periode nach rechts und sinkt in der Gruppe nach unten.",
    musterantwort: "Die Elektronegativität (EN) ist ein Maß für die Fähigkeit eines Atoms, Bindungselektronen an sich zu ziehen (Fluor = 4, höchster Wert, keine Einheit). Sie steigt innerhalb einer Periode von links nach rechts (steigende Kernladung) und sinkt innerhalb einer Gruppe von oben nach unten (Abschirmung durch zusätzliche Schalen).",
    falsch: [
      "Die Elektronegativität ist die Energie, die zur Abspaltung eines Protons nötig ist (Cäsium = 4, höchster Wert). Sie sinkt von links nach rechts und steigt von oben nach unten.",
      "Die Elektronegativität ist die elektrische Ladung eines Ions in Coulomb. Sie ist innerhalb einer Gruppe konstant und steigt nur von rechts nach links.",
      "Die Elektronegativität ist die Fähigkeit eines Atoms, Elektronen abzugeben (Fluor = 0, niedrigster Wert). Sie steigt von oben nach unten, weil größere Atome mehr Elektronen besitzen.",
    ],
    erklaerung: "Nach Mulliken: EN = ½ (Ionisierungsenergie + Elektronenaffinität). Geringe EN: Metalle links unten; hohe EN: F, O, Cl, N rechts oben.",
    seiten: "S. 157–158, 278–279",
  },
  {
    nr: 23, thema: "bdg",
    frage: "Beschreiben sie die verschiedenen Arten chemischer Bindungen (Atombindung, Metallbindung und Ionenbindung). Worauf beruht das Bestreben der Atome diese chemischen Bindungen einzugehen?",
    richtig: "Ionenbindung: Elektronenübertragung, Anziehung der Ionen; Atombindung: gemeinsame Elektronenpaare; Metallbindung: Atomrümpfe im Elektronengas. Ziel: Edelgaskonfiguration (Oktett).",
    musterantwort: "Ionenbindung (Metall + Nichtmetall): Elektronenübertragung, ungerichtete elektrostatische Anziehung von Kationen und Anionen im Ionengitter. Atombindung (Nichtmetall + Nichtmetall): gemeinsame, gerichtete Elektronenpaare. Metallbindung (Metall + Metall): positive Atomrümpfe im frei beweglichen Elektronengas. Bestreben: Erreichen der Edelgaskonfiguration (Oktett) – ein energetisch günstigerer Zustand.",
    falsch: [
      "Ionenbindung (Nichtmetall + Nichtmetall): gemeinsame Elektronenpaare. Atombindung (Metall + Nichtmetall): Elektronenübertragung. Metallbindung: Wasserstoffbrücken zwischen Metallatomen. Bestreben: möglichst viele ungepaarte Elektronen zu erhalten.",
      "Alle drei Bindungsarten beruhen auf der Anziehung zwischen Protonen verschiedener Atome. Bestreben: möglichst große Atomradien zu erreichen, um die Masse zu erhöhen.",
      "Ionenbindung: gerichtete Bindung zwischen zwei Molekülen. Atombindung: ungerichtete Anziehung zwischen Ionen. Metallbindung: Elektronen sind fest an einzelne Atome gebunden. Bestreben: möglichst hohe Energie zu erreichen.",
    ],
    erklaerung: "Edelgase kommen als einzige Elementgruppe ausschließlich atomar vor – ihr Oktett macht sie reaktionsträge. Alle anderen Elemente haben unvollständige Valenzschalen und gehen Bindungen ein.",
    seiten: "S. 171–175, 193–194, 298, 301",
  },
  {
    nr: 24, thema: "bdg",
    frage: "Was versteht man unter Koordinationszahl? Erklären Sie den Begriff anhand von Kochsalz.",
    richtig: "Die Koordinationszahl ist die Anzahl der nächsten Nachbarn eines Teilchens. In NaCl ist jedes Na⁺ von 6 Cl⁻ umgeben und umgekehrt → Koordinationszahl 6.",
    musterantwort: "Die Koordinationszahl (KZ) ist die Anzahl der nächsten Nachbarn (Gegenionen) eines Teilchens im Gitter. Im Kochsalz (NaCl) ist jedes Na⁺ von 6 Cl⁻ umgeben und jedes Cl⁻ von 6 Na⁺ → Koordinationszahl 6 (Na⁺ sitzen in den Oktaederlücken der Cl⁻-Packung).",
    falsch: [
      "Die Koordinationszahl ist die Anzahl der Elektronen, die bei der Bindung übertragen werden. Im Kochsalz gibt Na genau 1 Elektron an Cl ab → Koordinationszahl 1.",
      "Die Koordinationszahl ist die Anzahl der Atome in einer Formeleinheit. NaCl besteht aus 2 Atomen → Koordinationszahl 2.",
      "Die Koordinationszahl ist die Anzahl der nächsten Nachbarn. Im Kochsalz ist jedes Na⁺ von 8 Cl⁻ umgeben (würfelförmig) → Koordinationszahl 8.",
    ],
    erklaerung: "Die Cl⁻-Ionen sind ca. doppelt so groß wie Na⁺ und bilden eine dichteste Kugelpackung; die kleinen Na⁺ besetzen die großen (Oktaeder-)Lücken, die von je sechs Kugeln umgeben sind.",
    seiten: "S. 138, 174, 177",
  },
  {
    nr: 25, thema: "bdg",
    frage: "Beschreiben Sie die Bildung eines Ionengitters. Welche Typen von Ionengittern kennen Sie (mit Beschreibung)?",
    richtig: "Ionen umgeben sich ungerichtet mit möglichst vielen Gegenionen (Gitterenergie wird frei). Typen: NaCl (KZ 6), CsCl (KZ 8), ZnS (KZ 4) – je nach Radienverhältnis.",
    musterantwort: "Kationen und Anionen ziehen sich ungerichtet elektrostatisch an; jedes Ion umgibt sich mit möglichst vielen Gegenionen – es entsteht ein Ionengitter, dabei wird Gitterenergie frei. Typen (abhängig vom Radienverhältnis): NaCl-Typ (KZ 6, Oktaederlücken), CsCl-Typ (KZ 8, Ionen etwa gleich groß), ZnS-Typ (KZ 4, Tetraederlücken, Anion mehr als doppelt so groß).",
    falsch: [
      "Kationen und Anionen bilden gerichtete Elektronenpaarbindungen und damit einzelne Salz-Moleküle; beim Zusammenlagern wird Energie verbraucht. Typen: NaCl-Typ (KZ 4), CsCl-Typ (KZ 6), ZnS-Typ (KZ 8).",
      "Gleich geladene Ionen lagern sich zusammen und bilden getrennte Kationen- und Anionenschichten. Es gibt nur einen einzigen Gittertyp, der unabhängig von der Ionengröße ist.",
      "Ionengitter entstehen durch Wasserstoffbrücken zwischen Ionen. Typen: kubisch-raumzentriert (KZ 8), hexagonal-dicht (KZ 12) und kubisch-flächenzentriert (KZ 12).",
    ],
    erklaerung: "Die Gitterenergie ist bei NaCl so groß (ca. −787 kJ/mol), dass die Gesamtreaktion Na + ½ Cl₂ → NaCl trotz Sublimation, Dissoziation und Ionisierung exotherm ist.",
    seiten: "S. 174, 177–183",
  },
  {
    nr: 26, thema: "bdg",
    frage: "Was versteht man unter einer σ-Bindung bzw. π-Bindung? Erklären Sie diese Begriffe mithilfe der Moleküle H₂ und N₂.",
    richtig: "σ-Bindung: Überlappung entlang der Kernachse; π-Bindung: seitliche Überlappung von p-Orbitalen. H₂ enthält eine σ-Bindung, N₂ eine σ- und zwei π-Bindungen.",
    musterantwort: "σ-Bindung: Überlappung von Orbitalen entlang der Kernverbindungsachse (keine Knotenfläche entlang der Achse), z. B. H₂ aus zwei 1s-Orbitalen; jede Einfachbindung ist eine σ-Bindung. π-Bindung: seitliche Überlappung von p-Orbitalen, Elektronendichte ober- und unterhalb der Achse. N₂: Dreifachbindung aus einer σ-Bindung (2pz–2pz) und zwei π-Bindungen (2px–2px, 2py–2py).",
    falsch: [
      "σ-Bindung: seitliche Überlappung von p-Orbitalen; π-Bindung: Überlappung entlang der Kernachse. H₂ enthält eine π-Bindung, N₂ drei σ-Bindungen.",
      "σ-Bindung: Bindung zwischen zwei Ionen; π-Bindung: Bindung zwischen zwei Metallatomen. H₂ und N₂ enthalten daher keine σ- oder π-Bindungen.",
      "σ-Bindung: Überlappung entlang der Kernachse; π-Bindung: seitliche Überlappung. H₂ enthält eine σ- und eine π-Bindung, N₂ zwei σ- und eine π-Bindung.",
    ],
    erklaerung: "Einfachbindung = 1 σ; Doppelbindung = 1 σ + 1 π; Dreifachbindung = 1 σ + 2 π. Im N₂ verschmelzen die beiden π-Bindungen zu einem zylindrischen Orbital.",
    seiten: "S. 240–244",
  },
  {
    nr: 27, thema: "bdg",
    frage: "Erklären Sie die Hybridisierung anhand des CH₄-Moleküls (Welche bzw. wie viele Hybridorbitale werden gebildet; Molekülstruktur).",
    richtig: "Das C-Atom hebt ein 2s-Elektron an und bildet aus einem s- und drei p-Orbitalen vier sp³-Hybridorbitale → vier σ-Bindungen, tetraedrisches Molekül mit 109,5°.",
    musterantwort: "Ein 2s-Elektron des C-Atoms wird in das leere 2p-Orbital angehoben; dann mischen sich ein s- und drei p-Orbitale zu vier gleichwertigen sp³-Hybridorbitalen. Diese zeigen in die Ecken eines Tetraeders und überlappen mit je einem H-1s-Orbital zu vier σ-Bindungen → tetraedrisches Molekül, Bindungswinkel 109,5°.",
    falsch: [
      "Das C-Atom bildet aus einem s- und zwei p-Orbitalen drei sp²-Hybridorbitale; das vierte H bindet an das übrige p-Orbital → trigonal-planares Molekül mit 120°.",
      "Das C-Atom bildet aus einem s- und einem p-Orbital zwei sp-Hybridorbitale, die je zwei H-Atome binden → lineares Molekül mit 180°.",
      "Beim CH₄ findet keine Hybridisierung statt: C bindet mit seinen zwei ungepaarten 2p-Elektronen je zwei H-Atome → quadratisch-planares Molekül mit 90°.",
    ],
    erklaerung: "Aus n Atomorbitalen entstehen n Hybridorbitale. Hybridisierung ist ein Modell zur Beschreibung der experimentell gefundenen Tetraederstruktur – nicht deren Ursache.",
    seiten: "S. 245–249, 251, 259",
  },
  {
    nr: 28, thema: "bdg",
    frage: "Erläutern Sie die Hybridisierung und dessen räumliche Orientierung in den Kohlenwasserstoffen Ethan, Ethen, Ethin und in Benzol.",
    richtig: "Ethan: sp³, tetraedrisch (109,5°). Ethen: sp², planar (120°), σ + π. Ethin: sp, linear (180°), σ + 2 π. Benzol: sp², ebener Ring mit delokalisiertem π-System.",
    musterantwort: "Ethan: sp³, tetraedrisch (109,5°), nur σ-Bindungen, frei drehbar um die C–C-Achse. Ethen: sp², trigonal-planar (120°), C=C aus σ + π, planar, keine Drehbarkeit. Ethin: sp, linear (180°), C≡C aus σ + 2 π. Benzol: sp², ebener Sechsring (120°), die p-Orbitale bilden ein über den Ring delokalisiertes π-System.",
    falsch: [
      "Ethan: sp, linear (180°). Ethen: sp³, tetraedrisch (109,5°). Ethin: sp², trigonal-planar (120°). Benzol: sp³, sesselförmiger Ring mit drei lokalisierten Doppelbindungen.",
      "Ethan, Ethen und Ethin sind alle sp³-hybridisiert und tetraedrisch; nur Benzol ist sp²-hybridisiert. Die Doppel- und Dreifachbindungen bestehen aus zwei bzw. drei σ-Bindungen.",
      "Ethan: sp², planar (120°), nicht drehbar. Ethen: sp³, tetraedrisch, frei drehbar. Ethin: sp, gewinkelt (105°). Benzol: sp, linear angeordnete C-Atome.",
    ],
    erklaerung: "Die π-Bindung verhindert die Rotation um die C=C-Achse. In Benzol sind alle C–C-Bindungen gleich lang (139 pm) – zwischen Einfach- (154 pm) und Doppelbindung (134 pm).",
    seiten: "S. 201, 251–252, 262–269, 272",
  },
  {
    nr: 29, thema: "bdg",
    frage: "Was versteht man unter einem Dipol (Elektronegativität, Partialladung, polar, Dipolmoment, inkl. Beispiel)?",
    richtig: "Ein Dipol entsteht bei polaren Bindungen zwischen Atomen verschiedener EN (δ+/δ−), wenn die Ladungsschwerpunkte nicht zusammenfallen; Dipolmoment µ in Debye. Beispiel: HCl, H₂O.",
    musterantwort: "Bei einer Atombindung zwischen Atomen unterschiedlicher Elektronegativität zieht das elektronegativere Atom das Bindungselektronenpaar stärker an: es erhält eine negative Partialladung δ−, der Partner δ+ (polare Bindung). Fallen die Ladungsschwerpunkte nicht zusammen, entsteht ein Dipol; seine Größe ist das Dipolmoment µ (Einheit Debye). Beispiel: δ+H–Clδ−, H₂O.",
    falsch: [
      "Ein Dipol entsteht, wenn zwei Atome gleicher Elektronegativität ein Elektronenpaar genau in der Mitte teilen; das Dipolmoment wird in Coulomb gemessen. Beispiel: Cl₂, O₂.",
      "Ein Dipol ist ein Ion mit zwei Ladungen, z. B. Mg²⁺ oder O²⁻; Partialladungen treten nur in Ionengittern auf.",
      "Jedes Molekül mit polaren Bindungen ist automatisch ein Dipol; die Geometrie spielt keine Rolle. Beispiel: CO₂ ist ein starker Dipol, weil beide C=O-Bindungen polar sind.",
    ],
    erklaerung: "Die Geometrie entscheidet: CO₂ ist linear, die Bindungsdipole heben sich auf → unpolares Molekül. H₂O ist gewinkelt → Dipolmolekül. ΔEN < 0,8 kovalent, 0,8–1,8 polar kovalent, > 1,8 ionisch.",
    seiten: "S. 274–279, 288",
  },
  {
    nr: 30, thema: "bdg",
    frage: "Beschreiben Sie an Beispielen die verschiedenen Arten intermolekularer Wechselwirkungen.",
    richtig: "Ion-Dipol, Dipol-Dipol (z. B. HCl), Wasserstoffbrücken (H an N/O/F, z. B. Wasser) und Van-der-Waals-Kräfte (temporäre/induzierte Dipole, z. B. zwischen unpolaren Molekülen).",
    musterantwort: "Ion-Dipol (Ionen und polare Moleküle, ca. 15 kJ/mol), Dipol-Dipol (zwischen polaren Molekülen, z. B. HCl), Wasserstoffbrückenbindung (H an N, O oder F gebunden, ca. 20 kJ/mol, z. B. Wasser, Alkohole) sowie Van-der-Waals-Kräfte (temporäre/induzierte Dipole, zwischen allen, v. a. unpolaren Molekülen; nehmen mit Molekülgröße zu).",
    falsch: [
      "Ionenbindung, Atombindung und Metallbindung – sie wirken zwischen Molekülen und sind mit 200–400 kJ/mol stärker als die Bindungen innerhalb eines Moleküls.",
      "Nur Wasserstoffbrücken: Sie treten zwischen allen Molekülen auf, auch zwischen unpolaren wie CH₄; Van-der-Waals-Kräfte gibt es nur zwischen Ionen.",
      "Van-der-Waals-Kräfte wirken nur zwischen Ionen (ca. 250 kJ/mol), Wasserstoffbrücken nur zwischen unpolaren Molekülen wie Edelgasen, Dipol-Dipol-Kräfte nur in Metallen.",
    ],
    erklaerung: "Zwischenmolekulare Kräfte sind meist < 50 kJ/mol und bestimmen physikalische Eigenschaften wie den Siedepunkt (z. B. HCl: 16 kJ/mol zwischen Molekülen vs. 431 kJ/mol für die H–Cl-Bindung).",
    seiten: "S. 280–287, 292–295",
  },
  {
    nr: 31, thema: "bdg",
    frage: "Beschreiben Sie die Besonderheiten der Verbindung H₂O.",
    richtig: "H₂O ist gewinkelt (ca. 105°) und ein Dipol; Wasserstoffbrücken bewirken hohen Siedepunkt, größte Dichte bei 4 °C und Ausdehnung beim Gefrieren (Eis schwimmt).",
    musterantwort: "H₂O ist gewinkelt (ca. 105°, sp³-Hybrid am O mit zwei freien Elektronenpaaren) und ein Dipolmolekül. Zwischen den Molekülen bilden sich Wasserstoffbrücken → relativ hoher Schmelz- und Siedepunkt, Dichteanomalie (größte Dichte bei 4 °C), Ausdehnung beim Gefrieren um fast 10 % (Eis schwimmt). Wasser ist außerdem amphiprotisch (Autoprotolyse).",
    falsch: [
      "H₂O ist linear gebaut (180°) und daher unpolar. Es bildet keine Wasserstoffbrücken, hat seine größte Dichte als Eis bei 0 °C und zieht sich beim Gefrieren zusammen.",
      "H₂O ist ein Ionengitter aus H⁺ und O²⁻; der hohe Siedepunkt entsteht durch die starke Ionenbindung. Reines Wasser ist ein sehr guter elektrischer Leiter.",
      "H₂O ist gewinkelt, aber unpolar, weil O und H die gleiche Elektronegativität haben; ohne Dipol liegen Schmelz- und Siedepunkt bei ca. −100 °C bzw. −80 °C.",
    ],
    erklaerung: "Ohne Dipolcharakter läge die Schmelztemperatur bei ca. −100 °C und die Siedetemperatur bei ca. −80 °C – alles Wasser wäre gasförmig. Das schwerere CO₂ (44 u) ist schon ab −78,5 °C gasförmig.",
    seiten: "S. 287–291, 417",
  },
  {
    nr: 32, thema: "bdg",
    frage: "Erläutern Sie mittels des Bändermodells die Unterschiede zwischen Metallen, Halbleitern und Isolatoren (inkl. Skizze).",
    richtig: "Metall: Valenz- und Leitungsband überlappen → leitet. Halbleiter: schmale verbotene Zone, Anregung möglich. Isolator: breite verbotene Zone, Leitungsband leer.",
    musterantwort: "Metalle: Valenzband und Leitungsband überlappen (bzw. Band nur teilweise besetzt) → freie Zustände, gute Leitung; Leitfähigkeit sinkt mit steigender Temperatur. Halbleiter: schmale verbotene Zone – durch thermische/optische Anregung gelangen Elektronen ins Leitungsband; Leitfähigkeit steigt mit der Temperatur. Isolatoren: volles Valenzband, leeres Leitungsband, breite verbotene Zone (Diamant ca. 5 eV) → keine Leitung.",
    falsch: [
      "Metalle: breite verbotene Zone zwischen vollem Valenz- und leerem Leitungsband. Isolatoren: Valenz- und Leitungsband überlappen. Halbleiter: haben gar kein Leitungsband.",
      "Metalle, Halbleiter und Isolatoren haben identische Bänder; sie unterscheiden sich nur in der Anzahl der Protonen. Die Leitfähigkeit aller drei steigt mit der Temperatur.",
      "Halbleiter: Valenz- und Leitungsband überlappen, Leitfähigkeit sinkt mit steigender Temperatur. Metalle: schmale verbotene Zone, Leitfähigkeit steigt mit der Temperatur. Isolatoren: halb gefülltes Leitungsband.",
    ],
    erklaerung: "Skizze: Metall – Bänder überlappen; Halbleiter – kleiner Bandabstand (z. B. Si); Isolator – großer Bandabstand. Dotierung: n-Halbleiter (z. B. As in Si, Donatoren) und p-Halbleiter (z. B. In in Si, Akzeptoren).",
    seiten: "S. 303, 308–316",
  },
  {
    nr: 33, thema: "reak",
    frage: "Was muss alles bei der Aufstellung von Reaktionsgleichungen berücksichtigt werden?",
    richtig: "Edukte → Produkte; Atombilanz (Massenerhaltung) nur über die Koeffizienten ausgleichen, nie über Indizes; Aggregatzustände (s, l, g, aq) und Bedingungen (Δ, Katalysator) angeben.",
    musterantwort: "Edukte links, Produkte rechts (→ vollständige Reaktion, ⇌ Gleichgewicht). Atome werden weder erzeugt noch vernichtet (Massenerhaltung) – ausgeglichen wird nur über die stöchiometrischen Koeffizienten, nie über die Indizes der Formeln. Zusätzlich Aggregatzustände (s, l, g, aq) sowie Bedingungen wie Temperatur (Δ) oder Katalysatoren angeben.",
    falsch: [
      "Die Indizes in den Formeln werden so verändert, dass links und rechts gleich viele Moleküle stehen; die Anzahl der Atome muss dabei nicht übereinstimmen.",
      "Edukte stehen rechts, Produkte links. Es genügt, dass die Summe der Koeffizienten auf beiden Seiten gleich ist; Aggregatzustände werden nie angegeben.",
      "Bei chemischen Reaktionen kann Masse verloren gehen, daher muss nur die Anzahl der Kohlenstoffatome ausgeglichen werden; Wasserstoff und Sauerstoff ergeben sich von selbst.",
    ],
    erklaerung: "Beispiel: H₂ + O₂ → H₂O ist unvollständig (2 O links, 1 O rechts). Richtig: 2 H₂(g) + O₂(g) → 2 H₂O(l) – 2 mol H₂ reagieren mit 1 mol O₂ zu 2 mol H₂O.",
    seiten: "S. 331–336",
  },
  {
    nr: 34, thema: "reak",
    frage: "Wie lautet die exakte Gleichung der Verbrennungsreaktion von Ethan (C₂H₆)?",
    richtig: "2 C₂H₆ + 7 O₂ → 4 CO₂ + 6 H₂O",
    falsch: [
      "C₂H₆ + 3 O₂ → 2 CO₂ + 3 H₂O",
      "2 C₂H₆ + 5 O₂ → 4 CO₂ + 6 H₂O",
      "C₂H₆ + 7 O₂ → 2 CO₂ + 3 H₂O",
    ],
    erklaerung: "Schrittweise: zuerst C (2 CO₂), dann H (3 H₂O), dann O: rechts 4 + 3 = 7 O-Atome → 7/2 O₂. Mit 2 multiplizieren, um den Bruch zu entfernen: 2 C₂H₆ + 7 O₂ → 4 CO₂ + 6 H₂O.",
    seiten: "S. 338–339",
  },
  {
    nr: 35, thema: "reak",
    frage: "Erklären Sie den Begriff „Reaktionsenthalpie“. Wann ist die Reaktionsenthalpie positiv bzw. negativ (mit Beispielen)?",
    richtig: "Die Reaktionsenthalpie ΔH = ΣH(Produkte) − ΣH(Edukte) ist die Reaktionswärme. Negativ bei exothermen (C + O₂ → CO₂), positiv bei endothermen Reaktionen (H₂O → H₂ + ½ O₂).",
    musterantwort: "Die Reaktionsenthalpie ΔH ist die bei einer Reaktion abgegebene oder aufgenommene Energie (Reaktionswärme): ΔH = ΣH(Produkte) − ΣH(Edukte). Negativ bei exothermen Reaktionen (Energie wird abgegeben), z. B. C + O₂ → CO₂, ΔH = −393,5 kJ. Positiv bei endothermen Reaktionen (Energie wird aufgenommen), z. B. H₂O → H₂ + ½ O₂, ΔH = +286 kJ.",
    falsch: [
      "Die Reaktionsenthalpie ist die Unordnung eines Systems. Sie ist positiv, wenn Energie frei wird (z. B. Verbrennung von Kohlenstoff), und negativ, wenn Energie aufgenommen wird (z. B. Elektrolyse von Wasser).",
      "Die Reaktionsenthalpie ist die Geschwindigkeit einer Reaktion. Sie ist positiv bei schnellen Reaktionen (z. B. Knallgas) und negativ bei langsamen (z. B. Rosten).",
      "Die Reaktionsenthalpie ist der absolute Wärmeinhalt eines Stoffes, der direkt gemessen werden kann. Sie ist bei allen Verbrennungen positiv und bei allen Zerfallsreaktionen negativ.",
    ],
    erklaerung: "Absolute Enthalpien sind nicht messbar, nur Änderungen. Nullpunkt: stabilste Form eines Elements bei 25 °C und 1,013 bar hat die Enthalpie 0.",
    seiten: "S. 355–358",
  },
  {
    nr: 36, thema: "reak",
    frage: "Was ist eine exotherme bzw. eine endotherme Reaktion? Nennen Sie Beispiele.",
    richtig: "Exotherm: Energie wird abgegeben, ΔH < 0 (z. B. Verbrennung von Kohlenstoff). Endotherm: Energie wird aufgenommen, ΔH > 0 (z. B. Elektrolyse von Wasser).",
    musterantwort: "Exotherm: Es wird Energie (meist Wärme) an die Umgebung abgegeben, die Produkte sind energieärmer als die Edukte, ΔH < 0 – z. B. Verbrennung von Kohlenstoff, Knallgasreaktion. Endotherm: Es wird Energie aufgenommen, die Produkte sind energiereicher, ΔH > 0 – z. B. Elektrolyse von Wasser, Brennen von Kalk (CaCO₃ → CaO + CO₂).",
    falsch: [
      "Exotherm: Es wird Energie aufgenommen, ΔH > 0 – z. B. Elektrolyse von Wasser. Endotherm: Es wird Energie abgegeben, ΔH < 0 – z. B. Verbrennung von Kohlenstoff.",
      "Exotherm: Reaktionen, die nur mit Katalysator ablaufen – z. B. Ammoniaksynthese. Endotherm: Reaktionen, die ohne Katalysator ablaufen – z. B. Rosten von Eisen.",
      "Exotherm: Reaktionen, bei denen Gase entstehen. Endotherm: Reaktionen, bei denen Feststoffe entstehen. Die Energie spielt dabei keine Rolle.",
    ],
    erklaerung: "Bei exothermen Reaktionen „steckt“ Energie in den Edukten (Brennstoff), die frei wird. Bei endothermen Reaktionen wird Energie in die Produkte „investiert“.",
    seiten: "S. 335, 355–356",
  },
  {
    nr: 37, thema: "reak",
    frage: "Was versteht man unter der Aktivierungsenergie? Benutzen Sie zu ihrer Erklärung auch ein Energiediagramm für eine exotherme bzw. endotherme Reaktion.",
    richtig: "Die Aktivierungsenergie ist die Energie zur Bildung reaktionsfähiger Teilchen („Aktivierungsberg“). Im Diagramm: exotherm → Produkte tiefer als Edukte, endotherm → höher.",
    musterantwort: "Die Aktivierungsenergie Eₐ ist der Energiebetrag, der zur Bildung reaktionsfähiger Teilchen nötig ist – ein „Aktivierungsberg“, den das System vor der Reaktion überwinden muss. Im Energiediagramm liegt der Berg über den Edukten; bei exothermen Reaktionen liegen die Produkte danach tiefer als die Edukte, bei endothermen höher.",
    falsch: [
      "Die Aktivierungsenergie ist die Energie, die nach der Reaktion frei wird. Im Energiediagramm liegen bei exothermen Reaktionen die Produkte höher als die Edukte, bei endothermen tiefer; einen Berg gibt es nicht.",
      "Die Aktivierungsenergie ist identisch mit der Reaktionsenthalpie ΔH. Im Energiediagramm ist sie der Abstand zwischen Edukten und Produkten.",
      "Die Aktivierungsenergie tritt nur bei endothermen Reaktionen auf; exotherme Reaktionen laufen immer sofort und ohne Energiezufuhr ab (z. B. Knallgas bei Raumtemperatur).",
    ],
    erklaerung: "Deshalb verbrennt Papier nicht spontan und H₂/O₂ lassen sich bei Raumtemperatur mischen. Nach Zufuhr von Eₐ (z. B. Funke) läuft eine exotherme Reaktion von selbst weiter.",
    seiten: "S. 361–364",
  },
  {
    nr: 38, thema: "reak",
    frage: "Was versteht man unter der Geschwindigkeit chemischer Reaktionen? Durch welche Faktoren wird die Reaktionsgeschwindigkeit beeinflusst? Begründen Sie ihre Aussagen.",
    richtig: "Die Reaktionsgeschwindigkeit ist die Konzentrationsänderung pro Zeit; sie steigt mit Konzentration, Druck (Gase), Temperatur, Oberfläche und durch Katalysatoren (mehr erfolgreiche Stöße).",
    musterantwort: "Die Reaktionsgeschwindigkeit beschreibt die zeitliche Änderung der Konzentrationen (Edukte nehmen ab, Produkte zu). Nach der Stoßtheorie hängt sie von der Zahl erfolgreicher Zusammenstöße ab. Einflüsse: höhere Konzentration und höherer Druck (bei Gasen) → mehr Stöße; höhere Temperatur → schnellere Teilchen, mehr Stöße ≥ Eₐ; Katalysator → kleinere Eₐ; größere Oberfläche (heterogene Gemische).",
    falsch: [
      "Die Reaktionsgeschwindigkeit ist die Menge an Energie, die pro Sekunde frei wird. Sie hängt nur von der Reaktionsenthalpie ab: je negativer ΔH, desto schneller die Reaktion.",
      "Die Reaktionsgeschwindigkeit ist für jede Reaktion eine feste Naturkonstante und lässt sich weder durch Temperatur noch durch Konzentration oder Katalysatoren verändern.",
      "Die Reaktionsgeschwindigkeit nimmt mit steigender Temperatur ab, weil die Teilchen zu schnell aneinander vorbeifliegen; eine höhere Konzentration verlangsamt die Reaktion, weil sich die Teilchen gegenseitig behindern.",
    ],
    erklaerung: "Merke: Je größer die Konzentration der Ausgangsstoffe, je höher die Temperatur und je niedriger die Aktivierungsenergie, desto größer die Reaktionsgeschwindigkeit. Beispiel Oberfläche: Holzklotz vs. Holzstaub (Staubexplosion).",
    seiten: "S. 365–383",
  },
  {
    nr: 39, thema: "reak",
    frage: "Was ist die Aktivierungsenergie und wie bestimmt sie die Reaktionsgeschwindigkeit?",
    richtig: "Die Aktivierungsenergie ist die Mindestenergie für einen erfolgreichen Stoß. Je niedriger Eₐ, desto mehr Stöße sind erfolgreich und desto schneller die Reaktion.",
    musterantwort: "Die Aktivierungsenergie Eₐ ist die Mindestenergie, mit der Teilchen zusammenstoßen müssen, damit der Stoß „erfolgreich“ ist und eine Reaktion eintritt. Je niedriger Eₐ, desto größer der Anteil erfolgreicher Stöße und desto größer die Reaktionsgeschwindigkeit (Arrhenius: k = A·e^(−Eₐ/RT)).",
    falsch: [
      "Die Aktivierungsenergie ist die Energie, die bei der Reaktion frei wird. Je größer Eₐ, desto schneller läuft die Reaktion ab, weil mehr Energie zur Verfügung steht.",
      "Die Aktivierungsenergie ist die Energie, die ein Katalysator verbraucht. Sie hat keinen Einfluss auf die Reaktionsgeschwindigkeit, nur auf die Lage des Gleichgewichts.",
      "Die Aktivierungsenergie ist die Mindestenergie für einen erfolgreichen Stoß. Je höher Eₐ, desto mehr Stöße sind erfolgreich und desto schneller die Reaktion.",
    ],
    erklaerung: "Arrhenius-Gleichung: k = A·e^(−Eₐ/RT) – kleines Eₐ oder hohes T → großes k (Geschwindigkeitskonstante).",
    seiten: "S. 363–364, 373–375",
  },
  {
    nr: 40, thema: "reak",
    frage: "Wie ist ein Katalysator definiert? Beschreiben Sie die Wirkungsweise eines Katalysators anhand einer Skizze des Reaktionsverlaufs einer chemischen Reaktion. Wie beeinflusst er die Reaktionsgeschwindigkeit?",
    richtig: "Ein Katalysator senkt die Aktivierungsenergie und wird nicht verbraucht. Skizze: niedrigerer Aktivierungsberg bei gleichem ΔH → schneller, Gleichgewichtslage unverändert.",
    musterantwort: "Ein Katalysator ist ein Stoff, der die Aktivierungsenergie einer Reaktion herabsetzt und sie dadurch stark beschleunigt; er nimmt teil, liegt aber am Ende unverändert vor (wird nicht verbraucht). Skizze: gleiche Edukt- und Produktniveaus (ΔH unverändert), aber ein niedrigerer Aktivierungsberg. Er erhöht die Reaktionsgeschwindigkeit, ändert aber nicht die Lage des Gleichgewichts.",
    falsch: [
      "Ein Katalysator ist ein Stoff, der bei der Reaktion vollständig verbraucht wird und dabei zusätzliche Energie liefert. Skizze: Produkte liegen tiefer als ohne Katalysator (ΔH wird negativer).",
      "Ein Katalysator erhöht die Aktivierungsenergie, damit die Reaktion kontrollierter abläuft. Er verlangsamt die Reaktion und verschiebt das Gleichgewicht auf die Produktseite.",
      "Ein Katalysator senkt die Aktivierungsenergie und verschiebt dadurch das Gleichgewicht vollständig auf die Produktseite; bei der Reaktion wird er in das Produkt eingebaut.",
    ],
    erklaerung: "Homogene Katalyse (gleiche Phase, z. B. H₃O⁺ bei der Veresterung) vs. heterogene Katalyse (feste Oberfläche, z. B. Fe-Katalysator bei der NH₃-Synthese, Pt/Rh im Autoabgaskatalysator). Enzyme sind Biokatalysatoren.",
    seiten: "S. 374–382, 393",
  },
  {
    nr: 41, thema: "ggw",
    frage: "Was versteht man unter Gleichgewichtszustand von chemischen Reaktionen?",
    richtig: "Ein Zustand, in dem Hin- und Rückreaktion gleich schnell ablaufen, sodass die Konzentrationen konstant bleiben – ein dynamisches Gleichgewicht.",
    musterantwort: "Ein Zustand, in dem sich die Konzentrationen nicht mehr ändern, weil Hin- und Rückreaktion gleich schnell ablaufen. Es ist ein dynamisches Gleichgewicht: Es werden weiterhin ständig Produkte gebildet und zerfallen; die Reaktion ist umkehrbar (⇌).",
    falsch: [
      "Ein Zustand, in dem alle Edukte vollständig zu Produkten umgesetzt sind und keine Reaktion mehr stattfindet (statisches Gleichgewicht).",
      "Ein Zustand, in dem die Konzentration der Edukte und der Produkte immer genau gleich groß ist.",
      "Ein Zustand, in dem die Hinreaktion doppelt so schnell abläuft wie die Rückreaktion, sodass sich die Produkte langsam anreichern.",
    ],
    erklaerung: "Der Gleichgewichtszustand liegt nicht immer auf der Produktseite – oft liegen Ausgangsstoffe und Produkte nebeneinander vor. Beispiele: Boudouard-Gleichgewicht, Ammoniaksynthese.",
    seiten: "S. 332, 384",
  },
  {
    nr: 42, thema: "ggw",
    frage: "Geben Sie ein Beispiel für eine chemische Gleichgewichtsreaktion. Definieren Sie die Gleichgewichtskonstante für diese Reaktion. Welche Werte kann die Gleichgewichtskonstante annehmen?",
    richtig: "Beispiel: N₂ + 3 H₂ ⇌ 2 NH₃ mit K = [NH₃]² / ([N₂]·[H₂]³). K ≫ 1: Produktseite; K ≈ 1: ähnliche Konzentrationen; K ≪ 1: Eduktseite.",
    musterantwort: "Beispiel: N₂ + 3 H₂ ⇌ 2 NH₃ mit K = [NH₃]² / ([N₂]·[H₂]³) – Produkt der Produktkonzentrationen durch Produkt der Eduktkonzentrationen, jeweils hoch den Koeffizienten. K ≫ 1: Gleichgewicht liegt auf der Produktseite; K ≈ 1: vergleichbare Konzentrationen; K ≪ 1: Gleichgewicht liegt auf der Seite der Ausgangsstoffe.",
    falsch: [
      "Beispiel: N₂ + 3 H₂ ⇌ 2 NH₃ mit K = ([N₂]·[H₂]³) / [NH₃]². K kann nur Werte zwischen 0 und 1 annehmen; K = 1 bedeutet vollständige Umsetzung.",
      "Beispiel: N₂ + 3 H₂ ⇌ 2 NH₃ mit K = 2·[NH₃] / ([N₂] + 3·[H₂]). K ist immer negativ bei exothermen und positiv bei endothermen Reaktionen.",
      "Beispiel: N₂ + 3 H₂ ⇌ 2 NH₃ mit K = [NH₃]² / ([N₂]·[H₂]³). K ist für jede Reaktion immer genau 1, weil Hin- und Rückreaktion gleich schnell sind.",
    ],
    erklaerung: "[ ] = molare Konzentration (mol/L). K hängt nicht von den Konzentrationen ab, wohl aber von der Temperatur. Weiteres Beispiel: Boudouard-Gleichgewicht C + CO₂ ⇌ 2 CO.",
    seiten: "S. 384–388, 391",
  },
  {
    nr: 43, thema: "ggw",
    frage: "Wie kann das Gleichgewicht einer chemischen Reaktion verändert (gestört) werden?",
    richtig: "Durch Änderung von Konzentration, Temperatur oder – bei Gasreaktionen – Druck (äußerer Zwang); ein Katalysator ändert die Gleichgewichtslage nicht.",
    musterantwort: "Durch Änderung der Reaktionsbedingungen („äußerer Zwang“): Konzentrationsänderung eines beteiligten Stoffes, Temperaturänderung (Erwärmung begünstigt die endotherme Teilreaktion) und – bei Reaktionen mit Gasen – Druckänderung (Druckerhöhung begünstigt die Seite mit weniger Gasteilchen). Ein Katalysator verändert die Gleichgewichtslage nicht.",
    falsch: [
      "Nur durch Zugabe eines Katalysators, der das Gleichgewicht auf die Produktseite verschiebt; Temperatur, Druck und Konzentration haben keinen Einfluss.",
      "Durch Temperaturänderung: Erwärmung begünstigt immer die exotherme Teilreaktion. Druckänderungen wirken sich bei allen Reaktionen aus, auch ohne Gase.",
      "Ein chemisches Gleichgewicht kann nicht gestört werden – ist es einmal eingestellt, bleibt es unabhängig von äußeren Bedingungen bestehen.",
    ],
    erklaerung: "Le Chatelier: Das Gleichgewicht weicht dem Zwang aus. Ein Katalysator beschleunigt nur die Einstellung des Gleichgewichts.",
    seiten: "S. 389–393",
  },
  {
    nr: 44, thema: "ggw",
    frage: "Wie ist das Prinzip von „Le Chatelier“ definiert? Wenden Sie dieses Prinzip bei der Haber-Bosch-Synthese (mit Reaktionsgleichung) an. Wie verschiebt sich das Gleichgewicht bei Temperatur- bzw. Druckänderung?",
    richtig: "„Flucht vor dem Zwang“: Das Gleichgewicht weicht aus. N₂ + 3 H₂ ⇌ 2 NH₃ (exotherm): Temperaturerhöhung → links (weniger NH₃), Druckerhöhung → rechts (mehr NH₃).",
    musterantwort: "„Flucht vor dem Zwang“: Wirkt auf ein System im Gleichgewicht ein äußerer Zwang, verschiebt sich das Gleichgewicht so, dass es dem Zwang ausweicht. N₂ + 3 H₂ ⇌ 2 NH₃, ΔH negativ (exotherm): Temperaturerhöhung verschiebt nach links (weniger NH₃); Druckerhöhung verschiebt nach rechts (4 mol Gas → 2 mol), mehr NH₃. Technisch: ca. 450 °C, 300–400 bar, Fe-Katalysator.",
    falsch: [
      "„Flucht vor dem Zwang“: Das Gleichgewicht verstärkt einen äußeren Zwang. N₂ + 3 H₂ ⇌ 2 NH₃ ist endotherm: Temperaturerhöhung verschiebt nach rechts, Druckerhöhung nach links.",
      "Das Prinzip besagt, dass ein Katalysator das Gleichgewicht verschiebt. N₂ + H₂ ⇌ NH₃: Temperatur und Druck haben keinen Einfluss auf die Ausbeute an NH₃.",
      "„Flucht vor dem Zwang“: N₂ + 3 H₂ ⇌ 2 NH₃, ΔH negativ: Temperaturerhöhung verschiebt nach rechts (mehr NH₃); Druckerhöhung verschiebt nach links, weil dabei mehr Gasteilchen entstehen.",
    ],
    erklaerung: "Die hohe Temperatur ist ein Kompromiss: Wegen der hohen Aktivierungsenergie (N≡N-Dreifachbindung) wäre die Reaktion bei Raumtemperatur unmessbar langsam, obwohl das Gleichgewicht dort fast ganz bei NH₃ liegt.",
    seiten: "S. 389, 394–395",
  },
  {
    nr: 45, thema: "sb",
    frage: "Was versteht man unter einer starken bzw. schwachen Säure (Beispiele mit Reaktionsgleichungen)?",
    richtig: "Eine starke Säure ist vollständig deprotoniert (HCl + H₂O → H₃O⁺ + Cl⁻), eine schwache nur teilweise (CH₃COOH + H₂O ⇌ CH₃COO⁻ + H₃O⁺).",
    musterantwort: "Eine starke Säure ist in Wasser vollständig deprotoniert (Protonentransfer vollständig), z. B. HCl + H₂O → H₃O⁺ + Cl⁻. Eine schwache Säure ist nur teilweise deprotoniert, Säuremoleküle und Ionen liegen im Gleichgewicht nebeneinander vor, z. B. CH₃COOH + H₂O ⇌ CH₃COO⁻ + H₃O⁺ oder HCN + H₂O ⇌ H₃O⁺ + CN⁻.",
    falsch: [
      "Eine starke Säure ist eine konzentrierte Säure, eine schwache Säure eine verdünnte; z. B. ist 1 M Essigsäure stark und 0,01 M Salzsäure schwach.",
      "Eine starke Säure nimmt in Wasser vollständig Protonen auf, z. B. HCl + H₃O⁺ → H₂Cl⁺ + H₂O; eine schwache Säure gibt Hydroxid-Ionen ab, z. B. CH₃COOH → CH₃CO⁺ + OH⁻.",
      "Eine starke Säure ist nur teilweise deprotoniert, z. B. HCl + H₂O ⇌ H₃O⁺ + Cl⁻; eine schwache Säure ist vollständig deprotoniert, z. B. CH₃COOH + H₂O → CH₃COO⁻ + H₃O⁺.",
    ],
    erklaerung: "Starke Säuren: HCl, HBr, HI, HNO₃, HClO₄, H₂SO₄. Alle Carbonsäuren sind schwach – 0,1 M Essigsäure enthält nur ca. 1 Acetat-Ion pro 100 CH₃COOH-Moleküle.",
    seiten: "S. 402–406, 411",
  },
  {
    nr: 46, thema: "sb",
    frage: "Erklären Sie anhand eines Beispiels den Begriff Ampholyt (amphiprotisch).",
    richtig: "Ein Ampholyt kann Säure und Base sein. Beispiel Wasser: mit NH₃ gibt es H⁺ ab (Säure), mit HCl nimmt es H⁺ auf (Base); daher Autoprotolyse.",
    musterantwort: "Ein Ampholyt kann – je nach Reaktionspartner – sowohl als Säure (Protonendonor) als auch als Base (Protonenakzeptor) reagieren. Beispiel Wasser: gegenüber NH₃ ist es Säure (NH₃ + H₂O ⇌ NH₄⁺ + OH⁻), gegenüber HCl ist es Base (HCl + H₂O → H₃O⁺ + Cl⁻); daher auch Autoprotolyse 2 H₂O ⇌ H₃O⁺ + OH⁻.",
    falsch: [
      "Ein Ampholyt ist ein Stoff, der weder als Säure noch als Base reagieren kann. Beispiel Wasser: Es gibt nie Protonen ab oder nimmt welche auf und ist daher immer neutral.",
      "Ein Ampholyt ist eine Säure, die mehrere Protonen abgeben kann. Beispiel: H₂SO₄ gibt stufenweise zwei Protonen ab.",
      "Ein Ampholyt ist ein Salz, das bei der Neutralisation entsteht. Beispiel: HCl + NaOH → NaCl + H₂O, wobei NaCl der Ampholyt ist.",
    ],
    erklaerung: "Nach Brønsted kann ein und dieselbe Substanz Säure und Base sein. Eine Reaktion, bei der ein Molekül Protonen auf Moleküle derselben Art überträgt, heißt Autoprotolyse.",
    seiten: "S. 417",
  },
  {
    nr: 47, thema: "sb",
    frage: "Erläutern Sie das Ionenprodukt des Wassers. Wie wird es erhalten?",
    richtig: "Aus der Autoprotolyse 2 H₂O ⇌ H₃O⁺ + OH⁻; [H₂O] ist konstant und wird einbezogen: K_W = [H₃O⁺]·[OH⁻] = 10⁻¹⁴ mol²/L² (25 °C).",
    musterantwort: "Aus der Autoprotolyse 2 H₂O ⇌ H₃O⁺ + OH⁻ folgt K = [H₃O⁺]·[OH⁻] / [H₂O]². Da nur ein winziger Teil des Wassers dissoziiert, ist [H₂O] konstant und wird in die Konstante einbezogen: K_W = [H₃O⁺]·[OH⁻] = 10⁻¹⁴ mol²/L² (bei 25 °C; in reinem Wasser je 10⁻⁷ mol/L, aus Leitfähigkeitsmessungen).",
    falsch: [
      "Das Ionenprodukt ist die Summe der Ionenkonzentrationen: K_W = [H₃O⁺] + [OH⁻] = 14 mol/L; es wird durch Wiegen von Wasser bestimmt.",
      "K_W = [H₂O]² / ([H₃O⁺]·[OH⁻]) = 10¹⁴; in reinem Wasser ist [H₃O⁺] = 1 mol/L und [OH⁻] = 10⁻¹⁴ mol/L.",
      "K_W = [H₃O⁺]·[OH⁻] = 10⁻⁷ mol²/L²; es ist unabhängig von der Autoprotolyse und gilt nur für saure Lösungen.",
    ],
    erklaerung: "[H₃O⁺] und [OH⁻] sind gekoppelt: Säurezugabe erhöht [H₃O⁺] und senkt automatisch [OH⁻] (und umgekehrt). Dest. Wasser ist daher ein schlechter elektrischer Leiter.",
    seiten: "S. 417–421",
  },
  {
    nr: 48, thema: "sb",
    frage: "Was versteht man unter dem pH-Wert (Definition)? In welchem Zusammenhang stehen pH-Wert und pOH-Wert zueinander?",
    richtig: "Der pH-Wert ist der negative dekadische Logarithmus der H₃O⁺-Konzentration: pH = −log[H₃O⁺]. Es gilt pH + pOH = 14.",
    musterantwort: "Der pH-Wert ist der negative dekadische Logarithmus der Hydronium-Ionen-Konzentration: pH = −log[H₃O⁺] (analog pOH = −log[OH⁻]). Aus K_W = 10⁻¹⁴ folgt pH + pOH = 14. pH < 7 sauer, pH = 7 neutral, pH > 7 alkalisch.",
    falsch: [
      "Der pH-Wert ist die Konzentration der Hydroxid-Ionen in mol/L: pH = [OH⁻]. pH und pOH sind immer gleich groß.",
      "Der pH-Wert ist der positive Logarithmus der H₃O⁺-Konzentration: pH = log[H₃O⁺]. Es gilt pH · pOH = 14.",
      "Der pH-Wert ist der negative Logarithmus der H₃O⁺-Konzentration. Es gilt pH − pOH = 7; pH > 7 bedeutet sauer.",
    ],
    erklaerung: "Je höher [H₃O⁺], desto kleiner der pH. Reines Wasser (25 °C): [H₃O⁺] = 10⁻⁷ mol/L → pH 7. pH-Werte können auch > 14 oder negativ sein.",
    seiten: "S. 422–425",
  },
  {
    nr: 49, thema: "sb",
    frage: "Beschreiben Sie die Begriffe „Säurekonstante“ bzw. „Basenkonstante“.",
    richtig: "Gleichgewichtskonstanten der Protolyse: K_A = [H₃O⁺][A⁻]/[HA], K_B = [HB⁺][OH⁻]/[B] – Maß für Säure- bzw. Basenstärke; je größer pK, desto schwächer.",
    musterantwort: "Die Säurekonstante K_A = [H₃O⁺]·[A⁻] / [HA] ist die Gleichgewichtskonstante der Reaktion HA + H₂O ⇌ H₃O⁺ + A⁻ ([H₂O] einbezogen) und ein Maß für die Säurestärke. Analog Basenkonstante K_B = [HB⁺]·[OH⁻] / [B]. Meist als pK_A = −log K_A bzw. pK_B angegeben: je größer pK, desto schwächer; für konjugierte Paare gilt pK_A + pK_B = 14.",
    falsch: [
      "Die Säurekonstante ist der pH-Wert einer 1-molaren Säure; die Basenkonstante ist der pOH-Wert einer 1-molaren Base. Je größer der pK_A, desto stärker die Säure.",
      "K_A = [HA] / ([H₃O⁺]·[A⁻]) ist ein Maß für die Basenstärke; K_B gibt an, wie viele Protonen eine Säure abgeben kann. Es gilt K_A + K_B = 14.",
      "Säure- und Basenkonstanten sind für alle Säuren bzw. Basen gleich (10⁻⁷) und hängen nur von der Temperatur ab; sie sagen nichts über die Stärke aus.",
    ],
    erklaerung: "Beispiele: Essigsäure K_A = 1,8·10⁻⁵, HCl K_A ≈ 10⁷; Ammoniak K_B = 1,8·10⁻⁵ (pK_B 4,75 → pK_A von NH₄⁺ = 9,25). Je stärker die Säure, desto schwächer ihre konjugierte Base.",
    seiten: "S. 429–435",
  },
  {
    nr: 50, thema: "sb",
    frage: "Was sind Indikatoren und wozu werden sie verwendet? Nennen Sie einige Indikatoren und ihre Eigenschaften.",
    richtig: "Indikatoren sind Farbstoffe (schwache organische Säuren/Basen), deren Farbe vom pH abhängt. Beispiele: Lackmus (rot/blau), Phenolphthalein (farblos/rosa), Blaukraut.",
    musterantwort: "Indikatoren sind Farbstoffe – schwache organische Säuren bzw. Basen –, deren protonierte Form (sauer) eine andere Farbe hat als die deprotonierte (alkalisch). Sie zeigen an, ob eine Lösung sauer, neutral oder alkalisch ist (z. B. bei Titrationen, nur wenige Tropfen). Beispiele: Lackmus (rot/blau), Phenolphthalein (farblos → rosa zwischen pH 8,2 und 10), Blaukrautsaft (rot/grünlich, gelb bei starken Laugen).",
    falsch: [
      "Indikatoren sind starke anorganische Säuren, die eine Lösung neutralisieren; man setzt sie in großen Mengen zu. Beispiele: HCl, H₂SO₄, HNO₃.",
      "Indikatoren sind Metalle, die in Lösung die Leitfähigkeit anzeigen. Beispiele: Zink (färbt sich rot), Kupfer (blau), Eisen (grün).",
      "Indikatoren sind Farbstoffe, die ausschließlich die Temperatur einer Lösung anzeigen. Beispiele: Lackmus wird bei Wärme blau, Phenolphthalein bei Kälte rosa.",
    ],
    erklaerung: "HIn ⇌ H⁺ + In⁻ (Farbe A ⇌ Farbe B). Weil Indikatoren selbst Säuren/Basen sind und den pH beeinflussen, setzt man nur 2–3 Tropfen ein.",
    seiten: "S. 398–399, 426–428",
  },
  {
    nr: 51, thema: "redox",
    frage: "Geben Sie alle Oxidationszahlen in MnO₂, KMnO₄, P₂O₅, CaF₂, PO₄³⁻ und HCl an. Schreiben Sie die Oxidationszahl direkt über das Elementsymbol.",
    richtig: "MnO₂: Mn +IV, O −II · KMnO₄: K +I, Mn +VII, O −II · P₂O₅: P +V, O −II · CaF₂: Ca +II, F −I · PO₄³⁻: P +V, O −II · HCl: H +I, Cl −I",
    falsch: [
      "MnO₂: Mn +II, O −I · KMnO₄: K +I, Mn +V, O −II · P₂O₅: P +II, O −V · CaF₂: Ca +I, F −II · PO₄³⁻: P +III, O −II · HCl: H −I, Cl +I",
      "MnO₂: Mn +IV, O −II · KMnO₄: K +I, Mn +VII, O −II · P₂O₅: P +V, O −II · CaF₂: Ca +II, F −I · PO₄³⁻: P +VIII, O −II · HCl: H +I, Cl −I",
      "MnO₂: Mn +IV, O −II · KMnO₄: K +I, Mn +VI, O −II · P₂O₅: P +V, O −II · CaF₂: Ca +II, F −II · PO₄³⁻: P +V, O −II · HCl: H +I, Cl −I",
    ],
    erklaerung: "Regeln: O fast immer −II, F immer −I, H mit Nichtmetallen +I, Alkalimetalle +I, Erdalkalimetalle +II. Summe = Gesamtladung: KMnO₄: +1 + x − 8 = 0 → Mn +VII; PO₄³⁻: x − 8 = −3 → P +V.",
    seiten: "S. 439–446",
  },
  {
    nr: 52, thema: "redox",
    frage: "Erklären Sie die Begriffe Oxidation, Reduktion, Oxidationsmittel und Reduktionsmittel.",
    richtig: "Oxidation: Elektronenabgabe. Reduktion: Elektronenaufnahme. Oxidationsmittel nehmen Elektronen auf (werden reduziert), Reduktionsmittel geben sie ab (werden oxidiert).",
    musterantwort: "Oxidation: Abgabe von Elektronen (Oxidationszahl steigt). Reduktion: Aufnahme von Elektronen (Oxidationszahl sinkt). Oxidationsmittel nehmen Elektronen auf – sie oxidieren andere Stoffe und werden selbst reduziert (z. B. O₂, Halogene). Reduktionsmittel geben Elektronen ab – sie reduzieren andere Stoffe und werden selbst oxidiert (z. B. Alkalimetalle, H₂, C).",
    falsch: [
      "Oxidation: Aufnahme von Elektronen. Reduktion: Abgabe von Elektronen. Oxidationsmittel geben Elektronen ab und werden dabei oxidiert; Reduktionsmittel nehmen Elektronen auf.",
      "Oxidation bedeutet ausschließlich Reaktion mit Sauerstoff, Reduktion ausschließlich Reaktion mit Wasserstoff; Oxidations- und Reduktionsmittel sind immer O₂ bzw. H₂.",
      "Oxidation: Abgabe von Protonen. Reduktion: Aufnahme von Protonen. Oxidationsmittel sind Säuren, Reduktionsmittel sind Basen.",
    ],
    erklaerung: "Ursprünglich (Lavoisier): Oxidation = Verbindung mit Sauerstoff, Reduktion = Entzug von Sauerstoff. Heute allgemein über die Elektronenübertragung definiert.",
    seiten: "S. 447–451",
  },
  {
    nr: 53, thema: "redox",
    frage: "Was ist eine Redoxreaktion. Geben Sie 2 Beispiele an.",
    richtig: "Eine Reaktion, bei der Elektronen übertragen werden und sich Oxidationszahlen ändern; Oxidation und Reduktion sind gekoppelt. Beispiele: 2 Na + Cl₂ → 2 NaCl; CuO + Mg → Cu + MgO.",
    musterantwort: "Eine Reaktion, bei der Elektronen von einem Reaktionspartner auf den anderen übertragen werden (Oxidationszahlen ändern sich); Oxidation und Reduktion sind immer gekoppelt, es sind zwei Redoxpaare beteiligt. Beispiele: 2 Na + Cl₂ → 2 NaCl; CuO + Mg → Cu + MgO (auch Zn + Cu²⁺ → Zn²⁺ + Cu).",
    falsch: [
      "Eine Reaktion, bei der Protonen von einer Säure auf eine Base übertragen werden. Beispiele: HCl + H₂O → H₃O⁺ + Cl⁻; NH₃ + H₂O ⇌ NH₄⁺ + OH⁻.",
      "Eine Reaktion, bei der nur eine Oxidation ohne Reduktion stattfindet. Beispiele: Na → Na⁺ + e⁻; Fe²⁺ → Fe³⁺ + e⁻ (freie Elektronen bleiben übrig).",
      "Eine Reaktion, bei der sich die Oxidationszahlen nicht ändern und keine Elektronen fließen. Beispiele: HCl + NaOH → NaCl + H₂O; CaCO₃ → CaO + CO₂.",
    ],
    erklaerung: "Da keine freien Elektronen auftreten können, muss jede Oxidation mit einer Reduktion gekoppelt sein: Red₁ + Ox₂ → Ox₁ + Red₂.",
    seiten: "S. 447–454",
  },
  {
    nr: 54, thema: "redox",
    frage: "Welche Bedeutung hat die Nernst'sche Gleichung für die Beschreibung elektrochemischer Vorgänge?",
    richtig: "Sie gibt das Redoxpotential in Abhängigkeit von den Konzentrationen an: E = E° + (RT/zF)·ln([Ox]/[Red]) – z. B. zur Berechnung der EMK.",
    musterantwort: "Sie beschreibt das Redoxpotential E eines Redoxsystems in Abhängigkeit von den Konzentrationen: E = E° + (R·T)/(z·F) · ln([Ox]/[Red]) (bei 25 °C: E = E° + 0,059/z · log([Ox]/[Red])). E° ist das für jedes Redoxpaar charakteristische Standardpotential. Damit lässt sich z. B. die EMK eines galvanischen Elements berechnen.",
    falsch: [
      "Sie beschreibt die Geschwindigkeit einer Redoxreaktion in Abhängigkeit von der Aktivierungsenergie: k = A·e^(−Eₐ/RT).",
      "Sie gibt an, dass das Redoxpotential eines Systems unabhängig von den Konzentrationen immer gleich dem Standardpotential E° ist.",
      "Sie beschreibt den pH-Wert einer Lösung: pH = −log[H₃O⁺]; mit elektrochemischen Vorgängen hat sie nichts zu tun.",
    ],
    erklaerung: "R = Gaskonstante, T = Temperatur, F = Faraday-Konstante, z = Zahl der übertragenen Elektronen. Bei [Ox] = [Red] = 1 gilt E = E°.",
    seiten: "S. 458, 460–462",
  },
  {
    nr: 55, thema: "redox",
    frage: "Skizzieren Sie den Aufbau eines galvanischen Elements (mit Beschreibung).",
    richtig: "Zn in ZnSO₄ und Cu in CuSO₄, getrennt durch Diaphragma, leitend verbunden; e⁻ fließen von Zn (Anode, −, Oxidation) zu Cu (Kathode, +, Reduktion); EMK 1,10 V.",
    musterantwort: "Daniell-Element: Ein Zn-Stab taucht in ZnSO₄-Lösung (Halbzelle Zn/Zn²⁺), ein Cu-Stab in CuSO₄-Lösung (Halbzelle Cu/Cu²⁺); beide Räume sind durch ein poröses Diaphragma getrennt und die Stäbe über einen Leiter verbunden. Elektronen fließen vom Zn zum Cu: Zn → Zn²⁺ + 2e⁻ (Oxidation, Minuspol/Anode), Cu²⁺ + 2e⁻ → Cu (Reduktion, Pluspol/Kathode); EMK = 1,10 V.",
    falsch: [
      "Zn- und Cu-Stab tauchen gemeinsam in dieselbe CuSO₄-Lösung ohne Verbindung. Elektronen fließen vom Cu zum Zn; Cu ist der Minuspol, an dem Oxidation stattfindet; EMK = 0,34 V.",
      "Beide Halbzellen enthalten dieselbe Zn/Zn²⁺-Lösung; eine äußere Spannungsquelle treibt den Strom. Am Zn findet Reduktion, am Cu Oxidation statt.",
      "Daniell-Element: Zn in ZnSO₄, Cu in CuSO₄, getrennt durch Diaphragma. Elektronen fließen vom Cu zum Zn: Cu wird oxidiert (Minuspol), Zn²⁺ wird reduziert (Pluspol); EMK = −1,10 V.",
    ],
    erklaerung: "Das größere Bestreben von Zn, Elektronen abzugeben (unedler als Cu), bestimmt die Richtung des Elektronenflusses. ΔE = E°(Cu) − E°(Zn) = 0,34 V − (−0,76 V) = 1,10 V.",
    seiten: "S. 456–459, 462",
  },
  {
    nr: 56, thema: "redox",
    frage: "Welche Korrosionsschutzmaßnahmen kennen Sie?",
    richtig: "1) Lacke/Kunststoffüberzüge. 2) Überzug mit edlerem Metall (nur solange intakt). 3) Überzug mit unedlerem Metall (Verzinken). 4) Opferanode aus unedlem Metall (Zn, Mg).",
    musterantwort: "1) Kunststoffüberzüge oder Lacke (verhindern Zutritt von Wasser). 2) Überziehen mit einem edleren Metall (Galvanisieren, z. B. Verzinnen, Verchromen – schützt nur, solange die Schicht intakt ist). 3) Überziehen mit einem unedleren Metall (Verzinken – Zink korrodiert statt Eisen). 4) Leitende Verbindung mit einem unedleren Metall als Opferanode (Zn, Mg, Al).",
    falsch: [
      "1) Verbinden von Eisen mit einem edleren Metall wie Kupfer, damit sich das Kupfer auflöst. 2) Regelmäßiges Befeuchten mit Salzwasser. 3) Kontakt zweier verschiedener Metalle herstellen.",
      "1) Opferanoden aus Gold oder Platin, die sich statt Eisen auflösen. 2) Verzinnen, das auch bei Rissen dauerhaft schützt, weil Zinn unedler als Eisen ist.",
      "Korrosionsschutz ist nur durch Verwendung von möglichst stark verunreinigtem Metall möglich, da Verunreinigungen Lokalelemente verhindern.",
    ],
    erklaerung: "Beim verzinnten Blech löst sich bei einem Haarriss das unedlere Eisen auf; beim verzinkten Blech korrodiert das unedlere Zink und schützt das Eisen. Manche Metalle (Al, Cr) schützen sich selbst durch Passivierung.",
    seiten: "S. 473–479",
  },
  {
    nr: 57, thema: "redox",
    frage: "Erklären Sie den Begriff „Elektrolyse“. (inkl. Beispiel).",
    richtig: "Erzwingen eines nicht freiwillig ablaufenden Redoxvorgangs durch Gleichspannung, z. B. Umkehrung des Daniell-Elements: Zn²⁺ + Cu → Zn + Cu²⁺ (≥ 1,10 V).",
    musterantwort: "Bei der Elektrolyse werden Redoxvorgänge, die nicht freiwillig ablaufen, durch Anlegen einer Gleichspannung (mind. Zersetzungsspannung) erzwungen. Beispiel: Umkehrung des Daniell-Elements Zn²⁺ + Cu → Zn + Cu²⁺ (Zn²⁺ wird reduziert, Cu oxidiert; ≥ 1,10 V). Technisch: Gewinnung von Alkalimetallen, Aluminium, Kupferraffination, Verchromen, Laden eines Akkus.",
    falsch: [
      "Bei der Elektrolyse laufen Redoxvorgänge freiwillig ab und liefern elektrische Energie. Beispiel: Zn + Cu²⁺ → Zn²⁺ + Cu im Daniell-Element (Batterie).",
      "Elektrolyse ist das Lösen eines Salzes in Wasser, wobei Ionen entstehen. Beispiel: NaCl(s) → Na⁺(aq) + Cl⁻(aq); dabei wird kein Strom benötigt.",
      "Elektrolyse ist die Neutralisation einer Säure mit einer Base unter Stromzufuhr. Beispiel: HCl + NaOH → NaCl + H₂O.",
    ],
    erklaerung: "In der Praxis braucht man mehr Spannung als berechnet, u. a. um den elektrischen Widerstand der Zelle zu überwinden. Auch das Laden eines Bleiakkus ist eine Elektrolyse.",
    seiten: "S. 472, 480–484",
  },
  {
    nr: 58, thema: "redox",
    frage: "Definieren Sie die Begriffe \"Anode\" und \"Kathode\".",
    richtig: "Kathode: Elektrode der Reduktion (bei Elektrolyse −, bei Batterie +). Anode: Elektrode der Oxidation (bei Batterie −, bei Elektrolyse +).",
    musterantwort: "Kathode: Elektrode, an der Reduktion stattfindet – in der Elektrolysezelle der negative Pol, im galvanischen Element (Batterie) der positive Pol. Anode: Elektrode, an der Oxidation stattfindet (zu ihr wandern Anionen) – im galvanischen Element negativ, in der Elektrolysezelle positiv. Die Bezeichnung richtet sich nach dem chemischen Prozess, nicht nach der Ladung.",
    falsch: [
      "Kathode: immer der Pluspol, an dem Oxidation stattfindet. Anode: immer der Minuspol, an dem Reduktion stattfindet – unabhängig davon, ob Batterie oder Elektrolyse.",
      "Anode: Elektrode, an der Reduktion stattfindet und zu der Kationen wandern. Kathode: Elektrode, an der Oxidation stattfindet. Die Bezeichnung richtet sich nach der Ladung.",
      "Anode und Kathode bezeichnen die beiden Elektrolytlösungen einer Zelle; die Anode enthält die Anionen, die Kathode die Kationen. Mit Oxidation und Reduktion haben sie nichts zu tun.",
    ],
    erklaerung: "Merkhilfe: Anode – Oxidation (beide mit Vokal), Kathode – Reduktion (beide mit Konsonant). Beim Daniell-Element ist Zn die Anode (−), Cu die Kathode (+).",
    seiten: "S. 457, 466–467, 484",
  },
];

FAECHER.push({
  id: "chemie",
  name: "Chemie",
  kurz: "Chemie",
  icon: "⚗️",
  untertitel: "Fragenkatalog CHE1VO/ACA1VO",
  beschreibung: "Alle 58 Fragen aus dem Fragenkatalog, jeweils mit 4 Antwortmöglichkeiten. Die richtige Antwort und die Erklärung stammen aus dem Skriptum (mit Seitenangabe).",
  quelleText: "Skriptum ACA1VO/CHE1VO",
  nrLabel: "Katalog Nr.",
  mehrfach: false,
  store: "chemiequiz-stats-v1",
  themen: THEMEN,
  fragen: FRAGEN,
});
}
